[package]
name = "codesearch-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
arrow.workspace = true
arrow-schema.workspace = true
codesearch-bridge.workspace = true
datafusion.workspace = true
deltalake.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
codesearch-bridge.workspace = true
tempfile = "3"
tokio.workspace = true
