FROM docker.io/library/python@sha256:810da6270e43d30a1f3e0e1eabbeb6fbd9d78ad9dd2e754d5297a3d6cb42df46
COPY wheels /opt/producer-wheels
RUN python3 -I -m pip --isolated --disable-pip-version-check install --no-cache-dir --no-index --find-links=/opt/producer-wheels --only-binary=:all: --require-hashes --no-deps --no-compile --target=/opt/producers -r /opt/producer-wheels/requirements.txt
ENV PATH=/opt/producers/bin:/usr/local/bin:/usr/bin:/bin
ENV PYTHONDONTWRITEBYTECODE=1
ENV UV_NO_CONFIG=1
ENV UV_PYTHON_DOWNLOADS=never
WORKDIR /capsule
USER 65532:65532
