[package]
name = "codesearch-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
arrow.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
blake3.workspace = true
datafusion.workspace = true
parking_lot.workspace = true
deltalake.workspace = true
thiserror.workspace = true
