default_job = "check"

[jobs.check]
command = [
  "cargo",
  "check",
  "--workspace",
  "--all-targets",
  "--color",
  "always",
]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--workspace",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
  "--",
  "-D",
  "warnings",
]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run", "--workspace", "--color", "always"]
need_stdout = true

[keybindings]
c = "job:check"
l = "job:clippy"
t = "job:test"
