# generated by datamodel-codegen:
#   filename:  request.schema.json

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum, StrEnum


class ArtifactSection1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heading: str
    kind: Literal["markdown"]


class Ecosystem(Enum):
    rust = "rust"
    python = "python"
    NoneType_None = None


class DiscoveryKind(StrEnum):
    features = "features"
    documentation = "documentation"
    release_notes = "release_notes"
    examples = "examples"


class DiscoverySelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: str | None = None
    kind: DiscoveryKind
    max_characters: int | None = Field(
        None,
        description="None requests the complete retained text; callers may request a bounded preview.",
        ge=0,
    )
    max_items: int | None = Field(32, ge=0)


class InspectionAspect(StrEnum):
    signature = "signature"
    availability = "availability"
    relationships = "relationships"
    documentation = "documentation"
    examples = "examples"
    source = "source"
    semantics = "semantics"
    runtime = "runtime"
    children = "children"
    members = "members"


class InspectionIntent(StrEnum):
    retained = "retained"
    execute_on_miss = "execute_on_miss"
    rerun = "rerun"


class Profile(Enum):
    static = "static"
    build = "build"
    runtime = "runtime"
    NoneType_None = None


class Action(StrEnum):
    status = "status"
    wait = "wait"
    cancel = "cancel"


class JobRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action | None = Action.status
    interest_token: str | None = None
    job_id: str | None = ""
    max_bytes: int | None = Field(None, ge=0)
    wait_seconds: int | None = Field(0, ge=0)


class ManifestRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    snapshot_id: str | None = Field("", description="The snapshot to describe.")


class OverviewRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(None, description="Narrow to one module subtree.")
    context_id: str | None = Field("", description="The context from `resolve_library`.")
    discovery: list[DiscoverySelection] | None = Field(
        None,
        description="Independently paged library-level feature/docs/note/example discovery; None uses bounded defaults.",
    )
    max_bytes: int | None = Field(
        None, description="Advisory byte budget; the configured inline budget bounds it.", ge=0
    )
    max_items: int | None = Field(
        None,
        description="Cap on child entries per namespace; the configured limit bounds it.",
        ge=0,
    )
    snapshot_id: str | None = Field(
        None, description="A specific snapshot; the context's current one when omitted."
    )


class ResearchSelection1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["default"]


class Ecosystem1(StrEnum):
    rust = "rust"
    python = "python"


class Freshness(StrEnum):
    cache_ok = "cache_ok"
    revalidate = "revalidate"
    offline = "offline"


class Mode(Enum):
    project = "project"
    upstream = "upstream"
    compare = "compare"
    revision = "revision"
    NoneType_None = None


class ResolveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allow_local_build: bool | None = Field(
        False,
        description="Whether the caller accepts a local rustdoc build when hosted JSON is unusable.\n\nHosted docs.rs JSON comes first, always (§4.1). This opts into the §4.4 fallback, which\ncompiles third-party code on a dated nightly inside a capsule and can take minutes. It is\na request, not a grant: the `build` profile must also be enabled and its images qualified,\nor the answer is `POLICY_DENIED` with the setup action.",
    )
    allow_prerelease: bool | None = Field(
        False, description="Whether a prerelease may satisfy an unversioned request."
    )
    allow_yanked: bool | None = Field(
        False, description="Whether a yanked release may be resolved."
    )
    default_features: bool | None = Field(
        None, description="Whether the caller's project enables default features, when known."
    )
    ecosystem: Ecosystem1 | None = Field(Ecosystem1.rust, description="Which ecosystem.")
    extras: list[str] | None = Field(
        None, description="Explicit Python extras, distinct from Rust feature selection."
    )
    features: list[str] | None = Field(
        None, description="Features the caller's project enables, when known."
    )
    freshness: Freshness | None = Field(
        Freshness.cache_ok, description="Freshness policy for this call."
    )
    mode: Mode | None = Field(
        None,
        description="Research mode; defaults to `project` when a version is given and `upstream` otherwise.",
    )
    name: str | None = Field("", description="Package name as the caller spelled it.")
    package_subdir: str | None = Field(
        None, description="Explicit package root within the repository; omitted means root."
    )
    python_version: str | None = Field(
        None,
        description="Exact analyzed Python interpreter version; never inferred from the worker.",
    )
    repository: str | None = Field(
        None, description="Canonical public GitHub repository URL for revision mode."
    )
    revision: str | None = Field(
        None, description="Full immutable commit SHA; exclusive with version."
    )
    target: str | None = Field(None, description="The caller's target triple, when known.")
    version: str | None = Field(
        None, description="Exact version. Omitted only for an explicit upstream question."
    )


class ResultSectionName(StrEnum):
    coverage = "coverage"
    signature = "signature"
    changes = "changes"
    aspects = "aspects"
    data = "data"


class RuntimeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attributes: list[str]
    module: str


class Scope(StrEnum):
    api = "api"
    docs = "docs"
    configuration = "configuration"
    release_notes = "release_notes"
    examples = "examples"
    relationships = "relationships"


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(
        None, description="Restrict symbol/fragment subjects to this namespace subtree."
    )
    context_id: str | None = Field("", description="The context from `resolve_library`.")
    cursor: str | None = Field(None, description="Continue a previous page.")
    kinds: list[str] | None = Field(
        None,
        description="Evidence families: `api`, `docs`, `examples`, `release_notes`, `features`, `source`.",
    )
    max_bytes: int | None = Field(
        None, description="Byte budget for the page; the configured inline budget bounds it.", ge=0
    )
    max_items: int | None = Field(
        None, description="Page size; the configured limit bounds it.", ge=0
    )
    query: str | None = Field("", description="The query.")
    snapshot_id: str | None = Field(
        None, description="A specific snapshot; the context's current one when omitted."
    )


class SemanticMethod(StrEnum):
    hover = "hover"
    definition = "definition"
    implementation = "implementation"
    references = "references"
    diagnostics = "diagnostics"


class StatusRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: str | None = None


class Utf8Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byte: int = Field(..., ge=0)
    line: int = Field(..., ge=0)


class Mode1(StrEnum):
    compile = "compile"
    typecheck = "typecheck"
    runtime = "runtime"


class Profile1(StrEnum):
    static = "static"
    build = "build"
    runtime = "runtime"


class VerifyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str
    max_bytes: int | None = Field(None, ge=0)
    mode: Mode1
    profile: Profile1 = Field(
        ...,
        description="The three execution profiles (§10).\n\nThe values are, in order: `static`, `build`, `runtime`.",
    )
    snapshot_id: str | None = None
    snippet: str
    test_intent: str | None = None


class ResearchRequest1(BaseModel):
    method: Literal["service_status"]
    params: StatusRequest


class ResearchRequest2(BaseModel):
    method: Literal["verify_usage"]
    params: VerifyRequest


class ResearchRequest3(BaseModel):
    method: Literal["job_control"]
    params: JobRequest


class ResearchRequest5(BaseModel):
    method: Literal["resolve_library"]
    params: ResolveRequest


class ResearchRequest6(BaseModel):
    method: Literal["library_overview"]
    params: OverviewRequest


class ResearchRequest7(BaseModel):
    method: Literal["search_evidence"]
    params: SearchRequest


class ResearchRequest10(BaseModel):
    method: Literal["snapshot_manifest"]
    params: ManifestRequest


class ArtifactSection2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["result"]
    name: ResultSectionName


class ArtifactSection(RootModel[ArtifactSection1 | ArtifactSection2]):
    root: ArtifactSection1 | ArtifactSection2 = Field(
        ..., description="A result projection is distinct from a Markdown heading selection."
    )


class AspectSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aspect: InspectionAspect
    cursor: str | None = None
    max_characters: int | None = Field(
        None,
        description="Requested text projection for documentation/examples. None requests complete text.",
        ge=0,
    )
    max_items: int | None = Field(32, ge=0)


class CompareRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_context_id: str | None = None
    after_snapshot_id: str | None = None
    alternative_cursor: str | None = Field(
        None,
        description="Continue alternatives within one changed key, independently of the changed-key page.",
    )
    before_context_id: str | None = None
    before_snapshot_id: str | None = None
    cursor: str | None = None
    ecosystem: Ecosystem | None = Field(
        None,
        description="Which package ecosystem a release belongs to.\n\nThe values are, in order: `rust`, `python`. No variant carries a doc comment -- see the\nmodule docs in [`crate::wire`].",
    )
    from_version: str | None = None
    max_bytes: int | None = Field(None, ge=0)
    max_items: int | None = Field(None, ge=0)
    name: str | None = None
    scopes: list[Scope] | None = None
    to_version: str | None = None


class InspectionOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intent: InspectionIntent | None = InspectionIntent.retained
    methods: list[SemanticMethod] | None = Field(
        [],
        description="Empty selects hover, definition, references and diagnostics for semantic inspection.",
    )
    position: Utf8Position | None = Field(
        None,
        description="Advanced override; zero-based UTF-8 byte position at a character boundary.",
    )
    profile: Profile | None = Field(
        None,
        description="Required only for execution: build for semantics, runtime for runtime objects.",
    )
    runtime: RuntimeSelection | None = Field(
        None,
        description="Explicit Python selection. Import and introspection hooks may execute in the runtime capsule.",
    )
    snippet: str | None = Field(
        None, description="Omitted uses the selected symbol's generated consumer."
    )


class ReadArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str | None = Field("", description="A service-issued artifact handle.")
    cursor: str | None = Field(None, description="Continue a previous read.")
    max_bytes: int | None = Field(
        None,
        description="Byte budget for this slice; the configured inline budget bounds it.",
        ge=0,
    )
    section: ArtifactSection | None = Field(
        None,
        description="One typed result projection or Markdown heading, instead of the complete artifact.",
    )


class ResearchSelection2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aspects: list[AspectSelection]
    mode: Literal["explicit"]


class ResearchSelection(RootModel[ResearchSelection1 | ResearchSelection2]):
    root: ResearchSelection1 | ResearchSelection2 = Field(
        ...,
        description="One authoritative inspection scope; old depth/aspects arguments are not accepted.",
    )


class ResearchRequest4(BaseModel):
    method: Literal["compare_releases"]
    params: CompareRequest


class ResearchRequest9(BaseModel):
    method: Literal["read_artifact"]
    params: ReadArtifactRequest


class InspectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str | None = Field("", description="The context from `resolve_library`.")
    definition_id: str | None = Field(
        None,
        description="Select one definition at this path, using an inspection candidate or search result.",
    )
    execution: InspectionOptions | None = Field(
        None, description="Retained execution selection and explicit execution intent (ADR-0026)."
    )
    max_bytes: int | None = Field(
        None, description="Byte budget; the configured inline budget bounds it.", ge=0
    )
    selection: ResearchSelection | None = Field(
        {"mode": "default"},
        description="One bounded preset or explicit independently paged aspects.",
        validate_default=True,
    )
    snapshot_id: str | None = Field(
        None, description="A specific snapshot; the context's current one when omitted."
    )
    symbol_path: str | None = Field(
        "", description="A qualified path, or a bare name when unambiguous."
    )


class ResearchRequest8(BaseModel):
    method: Literal["inspect_symbol"]
    params: InspectRequest


class ResearchRequest(
    RootModel[
        ResearchRequest1
        | ResearchRequest2
        | ResearchRequest3
        | ResearchRequest4
        | ResearchRequest5
        | ResearchRequest6
        | ResearchRequest7
        | ResearchRequest8
        | ResearchRequest9
        | ResearchRequest10
    ]
):
    root: (
        ResearchRequest1
        | ResearchRequest2
        | ResearchRequest3
        | ResearchRequest4
        | ResearchRequest5
        | ResearchRequest6
        | ResearchRequest7
        | ResearchRequest8
        | ResearchRequest9
        | ResearchRequest10
    ) = Field(
        ...,
        description="Authoritative request schemas for implemented research methods.",
        title="ResearchRequest",
    )
