# generated by datamodel-codegen:
#   filename:  request.schema.json

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum, StrEnum


class ArtifactSection1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heading: str
    kind: Literal["markdown"]


class Ecosystem(Enum):
    rust = "rust"
    python = "python"
    NoneType_None = None


class DiscoveryKind(StrEnum):
    features = "features"
    documentation = "documentation"
    release_notes = "release_notes"
    examples = "examples"


class DiscoverySelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: str | None = None
    kind: DiscoveryKind
    max_characters: str | None = Field(
        None,
        description="None requests the complete retained text; callers may request a bounded preview.",
        pattern="^(?:(?:1[0-9]{4}|[2-5][0-9]{4}|6(?:0[0-9]{3}|[1-4][0-9]{3}|5(?:0[0-9]{2}|[1-4][0-9]{2}|5(?:0[0-9]{1}|[1-2][0-9]{1}|3[0-6][0-9]{0}))))|[1-9][0-9]{0,3})$",
    )
    max_items: str | None = Field(
        "32", pattern="^(?:10(?:0[0-9]{1}|[1-1][0-9]{1}|2[0-4][0-9]{0})|[1-9][0-9]{0,2})$"
    )


class InspectionAspect(StrEnum):
    signature = "signature"
    availability = "availability"
    relationships = "relationships"
    documentation = "documentation"
    examples = "examples"
    source = "source"
    semantics = "semantics"
    runtime = "runtime"
    children = "children"
    members = "members"


class InspectionIntent(StrEnum):
    retained = "retained"
    execute_on_miss = "execute_on_miss"
    rerun = "rerun"


class Profile(Enum):
    static = "static"
    build = "build"
    runtime = "runtime"
    NoneType_None = None


class Action(StrEnum):
    status = "status"
    wait = "wait"
    cancel = "cancel"


class JobRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action | None = Action.status
    interest_token: str | None = None
    job_id: str = Field(..., min_length=1)
    max_bytes: str | None = Field(
        None,
        pattern="^(?:(?:1(?:0(?:2[4-9][0-9]{0}|[3-8][0-9]{1}|9[0-9]{1})|[1-8][0-9]{2}|9[0-9]{2})|[2-8][0-9]{3}|9[0-9]{3})|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{4,18})$",
    )
    wait_seconds: str | None = Field("0", pattern="^(?:0|10|[1-9][0-9]{0,0})$")


class ManifestRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    snapshot_id: str = Field(
        ..., description="The snapshot to describe.", min_length=1, pattern="^snap_[0-9a-f]{64}$"
    )


class OverviewRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(None, description="Narrow to one module subtree.")
    context_id: str = Field(
        ...,
        description="The context from `resolve_library`.",
        min_length=1,
        pattern="^ctx_[0-9a-f]{64}$",
    )
    discovery: list[DiscoverySelection] | None = Field(
        None,
        description="Independently paged library-level feature/docs/note/example discovery; None uses bounded defaults.",
        max_length=4,
        min_length=0,
    )
    max_bytes: str | None = Field(
        None,
        description="Advisory byte budget; the configured inline budget bounds it.",
        pattern="^(?:(?:1(?:0(?:2[4-9][0-9]{0}|[3-8][0-9]{1}|9[0-9]{1})|[1-8][0-9]{2}|9[0-9]{2})|[2-8][0-9]{3}|9[0-9]{3})|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{4,18})$",
    )
    max_items: str | None = Field(
        None,
        description="Cap on child entries per namespace; the configured limit bounds it.",
        pattern="^(?:1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    snapshot_id: str | None = Field(
        None,
        description="A specific snapshot; the context's current one when omitted.",
        pattern="^snap_[0-9a-f]{64}$",
    )


class ResearchSelection1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["default"]


class Ecosystem1(StrEnum):
    rust = "rust"
    python = "python"


class Freshness(StrEnum):
    cache_ok = "cache_ok"
    revalidate = "revalidate"
    offline = "offline"


class Mode(Enum):
    project = "project"
    upstream = "upstream"
    compare = "compare"
    revision = "revision"
    NoneType_None = None


class ResolveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allow_local_build: bool | None = Field(
        False,
        description="Whether the caller accepts a local rustdoc build when hosted JSON is unusable.\n\nHosted docs.rs JSON comes first, always (§4.1). This opts into the §4.4 fallback, which\ncompiles third-party code on a dated nightly inside a capsule and can take minutes. It is\na request, not a grant: the `build` profile must also be enabled and its images qualified,\nor the answer is `POLICY_DENIED` with the setup action.",
    )
    allow_prerelease: bool | None = Field(
        False, description="Whether a prerelease may satisfy an unversioned request."
    )
    allow_yanked: bool | None = Field(
        False, description="Whether a yanked release may be resolved."
    )
    default_features: bool | None = Field(
        None, description="Whether the caller's project enables default features, when known."
    )
    ecosystem: Ecosystem1 = Field(..., description="Which ecosystem.")
    extras: list[str] | None = Field(
        None, description="Explicit Python extras, distinct from Rust feature selection."
    )
    features: list[str] | None = Field(
        None, description="Features the caller's project enables, when known."
    )
    freshness: Freshness | None = Field(
        Freshness.cache_ok, description="Freshness policy for this call."
    )
    mode: Mode | None = Field(
        None,
        description="Research mode; defaults to `project` when a version is given and `upstream` otherwise.",
    )
    name: str = Field(..., description="Package name as the caller spelled it.", min_length=1)
    package_subdir: str | None = Field(
        None, description="Explicit package root within the repository; omitted means root."
    )
    python_version: str | None = Field(
        None,
        description="Exact analyzed Python interpreter version; never inferred from the worker.",
    )
    repository: str | None = Field(
        None, description="Canonical public GitHub repository URL for revision mode."
    )
    revision: str | None = Field(
        None, description="Full immutable commit SHA; exclusive with version."
    )
    target: str | None = Field(None, description="The caller's target triple, when known.")
    version: str | None = Field(
        None, description="Exact version. Omitted only for an explicit upstream question."
    )


class ResultSectionName(StrEnum):
    envelope = "envelope"
    coverage = "coverage"
    signature = "signature"
    changes = "changes"
    aspects = "aspects"
    data = "data"


class RuntimeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attributes: list[str]
    module: str


class Scope(StrEnum):
    api = "api"
    docs = "docs"
    configuration = "configuration"
    release_notes = "release_notes"
    examples = "examples"
    relationships = "relationships"


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(
        None, description="Restrict symbol/fragment subjects to this namespace subtree."
    )
    context_id: str = Field(
        ...,
        description="The context from `resolve_library`.",
        min_length=1,
        pattern="^ctx_[0-9a-f]{64}$",
    )
    cursor: str | None = Field(None, description="Continue a previous page.")
    kinds: list[str] | None = Field(
        None,
        description="Evidence families: `api`, `docs`, `examples`, `release_notes`, `features`, `source`.",
    )
    max_bytes: str | None = Field(
        None,
        description="Byte budget for the page; the configured inline budget bounds it.",
        pattern="^(?:(?:1(?:0(?:2[4-9][0-9]{0}|[3-8][0-9]{1}|9[0-9]{1})|[1-8][0-9]{2}|9[0-9]{2})|[2-8][0-9]{3}|9[0-9]{3})|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{4,18})$",
    )
    max_items: str | None = Field(
        None,
        description="Page size; the configured limit bounds it.",
        pattern="^(?:1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    query: str = Field(..., description="The query.", min_length=1)
    snapshot_id: str | None = Field(
        None,
        description="A specific snapshot; the context's current one when omitted.",
        pattern="^snap_[0-9a-f]{64}$",
    )


class SemanticMethod(StrEnum):
    hover = "hover"
    definition = "definition"
    implementation = "implementation"
    references = "references"
    diagnostics = "diagnostics"


class StatusRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: str | None = None


class Utf8Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byte: int = Field(..., ge=0)
    line: int = Field(..., ge=0)


class Mode1(StrEnum):
    compile = "compile"
    typecheck = "typecheck"
    runtime = "runtime"


class Profile1(StrEnum):
    static = "static"
    build = "build"
    runtime = "runtime"


class VerifyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str = Field(
        ...,
        description="Binds a release to an environment and a research mode.",
        pattern="^ctx_[0-9a-f]{64}$",
    )
    max_bytes: str | None = Field(
        None,
        pattern="^(?:0|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    mode: Mode1 | None = Mode1.typecheck
    profile: Profile1 | None = Field(
        Profile1.build,
        description="The three execution profiles (§10).\n\nThe values are, in order: `static`, `build`, `runtime`.",
    )
    snapshot_id: str | None = Field(
        None,
        description="Names one immutable set of evidence available for a context.",
        pattern="^snap_[0-9a-f]{64}$",
    )
    snippet: str
    test_intent: str | None = None


class ResearchRequest1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["resolve_library"]
    params: ResolveRequest


class ResearchRequest2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["library_overview"]
    params: OverviewRequest


class ResearchRequest3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["search_evidence"]
    params: SearchRequest


class ResearchRequest6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["verify_usage"]
    params: VerifyRequest


class ResearchRequest8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["job_control"]
    params: JobRequest


class ResearchRequest9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["service_status"]
    params: StatusRequest


class ResearchRequest10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["snapshot_manifest"]
    params: ManifestRequest


class ArtifactSection2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["result"]
    name: ResultSectionName


class ArtifactSection(RootModel[ArtifactSection1 | ArtifactSection2]):
    root: ArtifactSection1 | ArtifactSection2 = Field(
        ..., description="A result projection is distinct from a Markdown heading selection."
    )


class AspectSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aspect: InspectionAspect
    cursor: str | None = None
    max_characters: str | None = Field(
        None,
        description="Requested text projection for documentation/examples. None requests complete text.",
        pattern="^(?:(?:1[0-9]{4}|[2-5][0-9]{4}|6(?:0[0-9]{3}|[1-4][0-9]{3}|5(?:0[0-9]{2}|[1-4][0-9]{2}|5(?:0[0-9]{1}|[1-2][0-9]{1}|3[0-6][0-9]{0}))))|[1-9][0-9]{0,3})$",
    )
    max_items: str | None = Field(
        "32", pattern="^(?:10(?:0[0-9]{1}|[1-1][0-9]{1}|2[0-4][0-9]{0})|[1-9][0-9]{0,2})$"
    )


class CompareRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_context_id: str | None = Field(
        None,
        description="Binds a release to an environment and a research mode.",
        pattern="^ctx_[0-9a-f]{64}$",
    )
    after_snapshot_id: str | None = Field(
        None,
        description="Names one immutable set of evidence available for a context.",
        pattern="^snap_[0-9a-f]{64}$",
    )
    alternative_cursor: str | None = Field(
        None,
        description="Continue alternatives within one changed key, independently of the changed-key page.",
    )
    before_context_id: str | None = Field(
        None,
        description="Binds a release to an environment and a research mode.",
        pattern="^ctx_[0-9a-f]{64}$",
    )
    before_snapshot_id: str | None = Field(
        None,
        description="Names one immutable set of evidence available for a context.",
        pattern="^snap_[0-9a-f]{64}$",
    )
    cursor: str | None = None
    ecosystem: Ecosystem | None = Field(
        None,
        description="Which package ecosystem a release belongs to.\n\nThe values are, in order: `rust`, `python`. No variant carries a doc comment -- see the\nmodule docs in [`crate::wire`].",
    )
    from_version: str | None = None
    max_bytes: str | None = Field(
        None,
        pattern="^(?:0|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    max_items: str | None = Field(
        None,
        pattern="^(?:0|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    name: str | None = None
    scopes: list[Scope] | None = None
    to_version: str | None = None


class InspectionOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intent: InspectionIntent | None = InspectionIntent.retained
    methods: list[SemanticMethod] | None = Field(
        [],
        description="Empty selects hover, definition, references and diagnostics for semantic inspection.",
        max_length=5,
        min_length=0,
    )
    position: Utf8Position | None = Field(
        None,
        description="Advanced override; zero-based UTF-8 byte position at a character boundary.",
    )
    profile: Profile | None = Field(
        None,
        description="Required only for execution: build for semantics, runtime for runtime objects.",
    )
    runtime: RuntimeSelection | None = Field(
        None,
        description="Explicit Python selection. Import and introspection hooks may execute in the runtime capsule.",
    )
    snippet: str | None = Field(
        None, description="Omitted uses the selected symbol's generated consumer."
    )


class ReadArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str = Field(..., description="A service-issued artifact handle.", min_length=1)
    cursor: str | None = Field(None, description="Continue a previous read.")
    max_bytes: str | None = Field(
        None,
        description="Byte budget for this slice; the configured inline budget bounds it.",
        pattern="^(?:(?:1(?:0(?:2[4-9][0-9]{0}|[3-8][0-9]{1}|9[0-9]{1})|[1-8][0-9]{2}|9[0-9]{2})|[2-8][0-9]{3}|9[0-9]{3})|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{4,18})$",
    )
    section: ArtifactSection | None = Field(
        None,
        description="One typed result projection or Markdown heading, instead of the complete artifact.",
    )


class ResearchSelection2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aspects: list[AspectSelection] = Field(..., max_length=10, min_length=1)
    mode: Literal["explicit"]


class ResearchSelection(RootModel[ResearchSelection1 | ResearchSelection2]):
    root: ResearchSelection1 | ResearchSelection2 = Field(
        ...,
        description="One authoritative inspection scope; old depth/aspects arguments are not accepted.",
    )


class ResearchRequest5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["compare_releases"]
    params: CompareRequest


class ResearchRequest7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["read_artifact"]
    params: ReadArtifactRequest


class InspectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str = Field(
        ...,
        description="The context from `resolve_library`.",
        min_length=1,
        pattern="^ctx_[0-9a-f]{64}$",
    )
    definition_id: str | None = Field(
        None,
        description="Select one definition at this path, using an inspection candidate or search result.",
    )
    execution: InspectionOptions | None = Field(
        None, description="Retained execution selection and explicit execution intent (ADR-0026)."
    )
    max_bytes: str | None = Field(
        None,
        description="Byte budget; the configured inline budget bounds it.",
        pattern="^(?:(?:1(?:0(?:2[4-9][0-9]{0}|[3-8][0-9]{1}|9[0-9]{1})|[1-8][0-9]{2}|9[0-9]{2})|[2-8][0-9]{3}|9[0-9]{3})|1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{4,18})$",
    )
    selection: ResearchSelection | None = Field(
        {"mode": "default"},
        description="One bounded preset or explicit independently paged aspects.",
        validate_default=True,
    )
    snapshot_id: str | None = Field(
        None,
        description="A specific snapshot; the context's current one when omitted.",
        pattern="^snap_[0-9a-f]{64}$",
    )
    symbol_path: str = Field(
        ..., description="A qualified path, or a bare name when unambiguous.", min_length=1
    )


class ResearchRequest4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["inspect_symbol"]
    params: InspectRequest


class ResearchRequest(
    RootModel[
        ResearchRequest1
        | ResearchRequest2
        | ResearchRequest3
        | ResearchRequest4
        | ResearchRequest5
        | ResearchRequest6
        | ResearchRequest7
        | ResearchRequest8
        | ResearchRequest9
        | ResearchRequest10
    ]
):
    root: (
        ResearchRequest1
        | ResearchRequest2
        | ResearchRequest3
        | ResearchRequest4
        | ResearchRequest5
        | ResearchRequest6
        | ResearchRequest7
        | ResearchRequest8
        | ResearchRequest9
        | ResearchRequest10
    ) = Field(
        ...,
        description="Every operation shares its native field, wire and MCP binding declaration.",
        title="ResearchRequest",
    )
