# generated by datamodel-codegen:
#   filename:  research-envelope.schema.json

from enum import StrEnum
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from typing import Any, Literal


class SchemaVersion(StrEnum):
    field_3_0 = "3.0"


class Status(StrEnum):
    ok = "ok"
    partial = "partial"
    pending = "pending"
    error = "error"


class Kind(StrEnum):
    registry_index_entry = "registry_index_entry"
    registry_version_metadata = "registry_version_metadata"
    crate_tarball = "crate_tarball"
    rustdoc_json = "rustdoc_json"
    cargo_manifest = "cargo_manifest"
    readme = "readme"
    changelog = "changelog"
    source_file = "source_file"
    other = "other"


class Artifact(BaseModel):
    artifact_id: str = Field(
        ...,
        description="`art_<64 hex>`, derived from the complete digest; used by `read_artifact`.",
    )
    compression: str | None = Field(
        ..., description="Transport compression that was removed before storage, e.g. `zstd`."
    )
    etag: str | None = Field(..., description="HTTP validator, when the server supplied one.")
    final_url: str | None = Field(
        ..., description="Where it was actually served from after redirects, when different."
    )
    kind: Kind = Field(..., description="What the artifact is.")
    last_modified: str | None = Field(
        ..., description="HTTP validator, when the server supplied one."
    )
    media_type: str = Field(
        ..., description="Media type of the stored bytes (after any transport decompression)."
    )
    retrieved_at: str = Field(
        ...,
        description="When it was retrieved, RFC 3339. Provenance only; never part of any identity.",
    )
    sha256: str = Field(..., description="Full SHA-256 of the stored bytes, lower-case hex.")
    size_bytes: int = Field(..., description="Size of the stored bytes.", ge=0)
    source_uri: str = Field(..., description="Where it was requested from.")


class ArtifactHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str = Field(
        ..., description="What the artifact contains, so a caller can decide whether to read it."
    )
    receipt: Artifact = Field(
        ...,
        description="Exact content identity and this acquisition's provenance. Pass receipt.artifact_id\nto read_artifact; repeated bytes may have different acquisition receipts.",
    )
    uri: str = Field(
        ...,
        description="Always a `library-evidence://` URI -- enforced by [`ArtifactUri`], not only by the schema.",
        pattern="^library-evidence://",
    )


class ArtifactSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heading: str
    kind: Literal["markdown"]


class DeliveryLimits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    effective_max_bytes: int | None = Field(..., ge=0)
    requested_max_bytes: int | None = Field(..., ge=0)


class DiagnosticCause(StrEnum):
    invalid_input = "invalid_input"
    not_found = "not_found"
    permission_denied = "permission_denied"
    corrupt_state = "corrupt_state"
    io = "io"
    capacity = "capacity"
    deadline = "deadline"
    invalid_plan = "invalid_plan"
    policy_denied = "policy_denied"
    unsupported = "unsupported"
    upstream = "upstream"
    transport = "transport"
    internal = "internal"


class Code(StrEnum):
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    AMBIGUOUS_PACKAGE = "AMBIGUOUS_PACKAGE"
    ARTIFACT_UNAVAILABLE = "ARTIFACT_UNAVAILABLE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    ENVIRONMENT_UNRESOLVED = "ENVIRONMENT_UNRESOLVED"
    ENVIRONMENT_MISMATCH = "ENVIRONMENT_MISMATCH"
    POLICY_DENIED = "POLICY_DENIED"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    INVALID_CURSOR = "INVALID_CURSOR"
    QUERY_FAILED = "QUERY_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class EvidenceClass(StrEnum):
    declared = "declared"
    statically_extracted = "statically_extracted"
    compiler_derived = "compiler_derived"
    typechecker_observed = "typechecker_observed"
    runtime_observed = "runtime_observed"
    agent_inferred = "agent_inferred"


class SourceVersionMatch(StrEnum):
    exact = "exact"
    compatible_claimed = "compatible_claimed"
    mismatched = "mismatched"
    unknown = "unknown"


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str = Field(..., description="The artifact this was read out of.")
    evidence_class: EvidenceClass = Field(
        ..., description="Which epistemic class this fact belongs to."
    )
    evidence_id: str = Field(..., description="Stable handle for citation.")
    excerpt: str = Field(..., description="A compact supporting quote.")
    locator: dict[str, Any] = Field(
        ...,
        description="Position within the artifact. Specialized as a discriminated union per producer.",
    )
    producer: str = Field(..., description="Which producer emitted this.")
    producer_version: str = Field(
        ..., description="The exact producer version, for reproducibility."
    )
    source_uri: AnyUrl = Field(..., description="Where the artifact came from.")
    source_version_match: SourceVersionMatch = Field(
        ..., description="How the source's version relates to the requested one."
    )
    subject: str = Field(
        ..., description="What the fact is about -- a symbol path, a setting, a release."
    )


class Freshness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    latest_verified: bool = Field(
        ...,
        description='Whether "this is the latest release" was actually revalidated. A cache hit alone is not\nevidence that a release is still latest.',
    )
    registry_checked_at: AwareDatetime | None = Field(
        ...,
        description="When the registry was last consulted, or `null` if it was not consulted at all.",
    )
    source_version_match: SourceVersionMatch = Field(
        ..., description="How the evidence's source version relates to the requested one."
    )


class State(StrEnum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancel_requested = "cancel_requested"
    cancelled = "cancelled"


class JobHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    job_id: str = Field(
        ...,
        description="Durable core job identity. Distinct from the request ID: jobs are shared and reusable.",
    )
    poll_after_ms: int = Field(
        ..., description="Advisory next-poll delay. Not a completion-time guarantee.", ge=0
    )
    stage: str = Field(
        ..., description="Which stage is executing, for a caller to report progress."
    )
    state: State = Field(..., description="Where the job is now.")


class RecoveryAction1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    arguments: dict[str, Any]
    kind: Literal["call_tool"]
    tool: str


class RecoveryAction3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["retry_after"]
    milliseconds: int = Field(..., ge=0)


class RecoveryAction4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["change_request"]
    reason: str


class RecoveryAction5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["operator_setup"]
    reason: str


class RecoveryAction6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["report_defect"]
    reason: str


class ResultSectionName(StrEnum):
    coverage = "coverage"
    signature = "signature"
    changes = "changes"
    aspects = "aspects"
    data = "data"


class Kind1(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"
    distribution_source = "distribution_source"
    stubs = "stubs"
    inventory = "inventory"
    runtime_api = "runtime_api"
    semantic_queries = "semantic_queries"
    usage_probes = "usage_probes"


class ScopeState(StrEnum):
    indexed = "indexed"
    partial = "partial"
    missing = "missing"
    unknown = "unknown"


class SubjectRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["symbol"]
    symbol_id: str


class SubjectRef2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition_id: str
    kind: Literal["definition"]


class SubjectRef3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["library"]
    release_id: str


class SubjectRef4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["feature"]
    name: str


class SubjectRef5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    heading: str
    kind: Literal["document"]


class SubjectRef6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    kind: Literal["example"]
    path: str


class SubjectRef(
    RootModel[SubjectRef1 | SubjectRef2 | SubjectRef3 | SubjectRef4 | SubjectRef5 | SubjectRef6]
):
    root: SubjectRef1 | SubjectRef2 | SubjectRef3 | SubjectRef4 | SubjectRef5 | SubjectRef6 = Field(
        ...,
        description="A reference carries its indexing domain. External paths never masquerade as local keys.",
    )


class ArtifactSection5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["result"]
    name: ResultSectionName


class ArtifactSection3(RootModel[ArtifactSection | ArtifactSection5]):
    root: ArtifactSection | ArtifactSection5 = Field(
        ..., description="A result projection is distinct from a Markdown heading selection."
    )


class DeliveryDescriptor1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limits: DeliveryLimits
    mode: Literal["inline"]


class RecoveryAction2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    cursor: str | None
    kind: Literal["read_artifact"]
    section: ArtifactSection3 | None


class RecoveryAction(
    RootModel[
        RecoveryAction1
        | RecoveryAction2
        | RecoveryAction3
        | RecoveryAction4
        | RecoveryAction5
        | RecoveryAction6
    ]
):
    root: (
        RecoveryAction1
        | RecoveryAction2
        | RecoveryAction3
        | RecoveryAction4
        | RecoveryAction5
        | RecoveryAction6
    ) = Field(
        ..., description="An actionable follow-up, never an instruction to execute automatically."
    )


class ResultSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    name: ResultSectionName


class ScopeAssessment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind1 = Field(
        ...,
        description="The kinds of evidence a producer can require or yield, and that `coverage.indexed` and\n`coverage.missing` name.\n\nThe values are, in order: `registry_metadata`, `crate_source`,\n`documentation_build_config`, `hosted_rustdoc_json`, `public_api`, `documentation`,\n`examples`, `release_notes`, `source_excerpts`.",
    )
    snapshot_id: str
    state: ScopeState
    subject: SubjectRef
    witness_id: str | None = Field(
        ...,
        description="A qualified fact establishing the selected state. Historical attempts remain retained.",
    )


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assessments: list[ScopeAssessment] = Field(
        ..., description="Requested evidence scopes assessed against qualified native facts."
    )
    details: RecoveryAction | None = Field(
        ...,
        description="When present, additional limitation text is retained in the exact coverage section.\nScope, assessments, indexed and missing remain the authoritative inline assessment.",
    )
    indexed: list[str] = Field(..., description="Evidence kinds that were successfully indexed.")
    limitations: list[str] = Field(..., description="Known reasons this result may not generalize.")
    missing: list[str] = Field(..., description="Evidence kinds that were expected but are absent.")
    scope: str = Field(..., description="What the result claims to cover, in prose.")


class DeliveryDescriptor2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    limits: DeliveryLimits
    mode: Literal["artifact"]
    read: RecoveryAction
    sections: list[ResultSection]


class DeliveryDescriptor(RootModel[DeliveryDescriptor1 | DeliveryDescriptor2]):
    root: DeliveryDescriptor1 | DeliveryDescriptor2 = Field(
        ...,
        description="Delivery changes representation, never the original research status or coverage.",
    )


class Diagnostic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actions: list[RecoveryAction]
    affected_ids: list[str]
    allowed: int | None = Field(..., ge=0)
    cause: DiagnosticCause
    correlation_id: str | None
    observed: int | None = Field(..., ge=0)
    rule: str | None
    stage: str


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Code = Field(..., description="The stable code a caller can branch on.")
    diagnostic: Diagnostic = Field(..., description="Structured origin and recovery evidence.")
    message: str = Field(..., description="Human-readable explanation. Not a stable interface.")
    next_action: str = Field(
        ...,
        description="What the caller should do instead. Blueprint §7.2 requires this, not just a code.",
    )
    retryable: bool = Field(
        ..., description="Whether retrying the identical request could succeed."
    )


class LibraryEnrichmentResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifacts: list[ArtifactHandle] = Field(
        ..., description="Bounded artifacts available for reading."
    )
    context_id: str | None = Field(..., description="The research context, or `null`.")
    coverage: Coverage = Field(..., description="What was looked at, and what was not.")
    data: dict[str, Any] = Field(..., description="Tool-specific payload.")
    delivery: DeliveryDescriptor = Field(..., description="Result-bounding accounting.")
    error: Error | None
    evidence: list[Evidence] = Field(..., description="Supporting facts with provenance.")
    freshness: Freshness = Field(..., description="Registry freshness.")
    job: JobHandle | None
    request_id: str = Field(..., description="Opaque per-request identifier.", min_length=1)
    schema_version: SchemaVersion = Field(..., description="Always `3.0` for this contract.")
    snapshot_id: str | None = Field(..., description="The snapshot read, or `null`.")
    status: Status = Field(
        ...,
        description="The four result statuses (blueprint §7.2).\n\nThe values are, in order: `ok`, `partial`, `pending`, `error`. `ok` means successful within\nthe declared coverage, not complete knowledge; `partial` carries usable evidence *and* gaps.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).",
    )
    summary: str = Field(..., description="One-line account of what this result establishes.")
