# generated by datamodel-codegen:
#   filename:  research-envelope.schema.json
#   timestamp: 2026-09-13T20:21:26+00:00

from enum import StrEnum
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field
from typing import Any


class SchemaVersion(StrEnum):
    field_1_0 = "1.0"


class Status(StrEnum):
    ok = "ok"
    partial = "partial"
    pending = "pending"
    error = "error"


class ArtifactHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str = Field(..., description="Stable handle, usable with `read_artifact`.")
    description: str = Field(
        ..., description="What the artifact contains, so a caller can decide whether to read it."
    )
    media_type: str = Field(..., description="The artifact's media type.")
    uri: str = Field(
        ...,
        description="Always a `library-evidence://` URI -- enforced by [`ArtifactUri`], not only by the schema.",
        pattern="^library-evidence://",
    )


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    indexed: list[str] = Field(..., description="Evidence kinds that were successfully indexed.")
    limitations: list[str] = Field(..., description="Known reasons this result may not generalize.")
    missing: list[str] = Field(..., description="Evidence kinds that were expected but are absent.")
    scope: str = Field(..., description="What the result claims to cover, in prose.")


class Code(StrEnum):
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    AMBIGUOUS_PACKAGE = "AMBIGUOUS_PACKAGE"
    ARTIFACT_UNAVAILABLE = "ARTIFACT_UNAVAILABLE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    ENVIRONMENT_UNRESOLVED = "ENVIRONMENT_UNRESOLVED"
    ENVIRONMENT_MISMATCH = "ENVIRONMENT_MISMATCH"
    POLICY_DENIED = "POLICY_DENIED"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    INVALID_CURSOR = "INVALID_CURSOR"


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Code = Field(..., description="The stable code a caller can branch on.")
    message: str = Field(..., description="Human-readable explanation. Not a stable interface.")
    next_action: str = Field(
        ...,
        description="What the caller should do instead. Blueprint §7.2 requires this, not just a code.",
    )
    retryable: bool = Field(
        ..., description="Whether retrying the identical request could succeed."
    )


class EvidenceClass(StrEnum):
    declared = "declared"
    statically_extracted = "statically_extracted"
    compiler_derived = "compiler_derived"
    typechecker_observed = "typechecker_observed"
    runtime_observed = "runtime_observed"
    agent_inferred = "agent_inferred"


class SourceVersionMatch(StrEnum):
    exact = "exact"
    compatible_claimed = "compatible_claimed"
    mismatched = "mismatched"
    unknown = "unknown"


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str = Field(..., description="The artifact this was read out of.")
    evidence_class: EvidenceClass = Field(
        ..., description="Which epistemic class this fact belongs to."
    )
    evidence_id: str = Field(..., description="Stable handle for citation.")
    excerpt: str = Field(..., description="A compact supporting quote.")
    locator: dict[str, Any] = Field(
        ...,
        description="Position within the artifact. Specialized as a discriminated union per producer.",
    )
    producer: str = Field(..., description="Which producer emitted this.")
    producer_version: str = Field(
        ..., description="The exact producer version, for reproducibility."
    )
    source_uri: AnyUrl = Field(..., description="Where the artifact came from.")
    source_version_match: SourceVersionMatch = Field(
        ..., description="How the source's version relates to the requested one."
    )
    subject: str = Field(
        ..., description="What the fact is about -- a symbol path, a setting, a release."
    )


class Freshness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    latest_verified: bool = Field(
        ...,
        description='Whether "this is the latest release" was actually revalidated. A cache hit alone is not\nevidence that a release is still latest.',
    )
    registry_checked_at: AwareDatetime | None = Field(
        ...,
        description="When the registry was last consulted, or `null` if it was not consulted at all.",
    )
    source_version_match: SourceVersionMatch = Field(
        ..., description="How the evidence's source version relates to the requested one."
    )


class State(StrEnum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancel_requested = "cancel_requested"
    cancelled = "cancelled"


class JobHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    job_id: str = Field(
        ...,
        description="Durable core job identity. Distinct from the request ID: jobs are shared and reusable.",
    )
    poll_after_ms: int = Field(
        ..., description="Advisory next-poll delay. Not a completion-time guarantee.", ge=0
    )
    stage: str = Field(
        ..., description="Which stage is executing, for a caller to report progress."
    )
    state: State = Field(..., description="Where the job is now.")


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    next_cursor: str | None = Field(
        ..., description="Opaque cursor for the next page, or `null` at the end."
    )
    returned: int = Field(..., description="How many entries this page carries.", ge=0)
    total_matches: int | None = Field(
        ..., description='Total matches when known. `null` means "not counted", never "zero".', ge=0
    )
    truncated: bool = Field(..., description="Whether output was cut short by a budget.")


class LibraryEnrichmentResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifacts: list[ArtifactHandle] = Field(
        ..., description="Bounded artifacts available for reading."
    )
    context_id: str | None = Field(..., description="The research context, or `null`.")
    coverage: Coverage = Field(..., description="What was looked at, and what was not.")
    data: dict[str, Any] = Field(..., description="Tool-specific payload.")
    error: Error | None
    evidence: list[Evidence] = Field(..., description="Supporting facts with provenance.")
    freshness: Freshness = Field(..., description="Registry freshness.")
    job: JobHandle | None
    pagination: Pagination = Field(..., description="Result-bounding accounting.")
    request_id: str = Field(..., description="Opaque per-request identifier.", min_length=1)
    schema_version: SchemaVersion = Field(..., description="Always `1.0` for this contract.")
    snapshot_id: str | None = Field(..., description="The snapshot read, or `null`.")
    status: Status = Field(
        ...,
        description="The four result statuses (blueprint §7.2).\n\nThe values are, in order: `ok`, `partial`, `pending`, `error`. `ok` means successful within\nthe declared coverage, not complete knowledge; `partial` carries usable evidence *and* gaps.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).",
    )
    summary: str = Field(..., description="One-line account of what this result establishes.")
