# generated by datamodel-codegen:
#   filename:  tool-data.schema.json

from enum import Enum, StrEnum
from pydantic import BaseModel, ConfigDict, Field, RootModel
from typing import Any, Literal


class EvidenceClass(StrEnum):
    declared = "declared"
    statically_extracted = "statically_extracted"
    compiler_derived = "compiler_derived"
    typechecker_observed = "typechecker_observed"
    runtime_observed = "runtime_observed"
    agent_inferred = "agent_inferred"


class Mode(StrEnum):
    compile = "compile"
    typecheck = "typecheck"
    runtime = "runtime"


class Profile(StrEnum):
    static = "static"
    build = "build"
    runtime = "runtime"


class State(StrEnum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancel_requested = "cancel_requested"
    cancelled = "cancelled"


class DefinitionsByKind(RootModel[int]):
    root: int = Field(..., ge=0)


class Encoding(StrEnum):
    utf8 = "utf8"
    base64 = "base64"


class AlternativeValue1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["inline"]
    value: Any


class ApiOrigin(StrEnum):
    rustdoc = "rustdoc"
    source = "source"
    stub = "stub"


class DeclaredKind(StrEnum):
    module = "module"
    struct = "struct"
    class_ = "class"
    attribute = "attribute"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    extern_type = "extern_type"
    import_ = "import"


class Kind(StrEnum):
    registry_index_entry = "registry_index_entry"
    registry_version_metadata = "registry_version_metadata"
    crate_tarball = "crate_tarball"
    rustdoc_json = "rustdoc_json"
    cargo_manifest = "cargo_manifest"
    readme = "readme"
    changelog = "changelog"
    source_file = "source_file"
    other = "other"


class Artifact(BaseModel):
    artifact_id: str = Field(
        ...,
        description="`art_<64 hex>`, derived from the complete digest; used by `read_artifact`.",
    )
    compression: str | None = Field(
        ..., description="Transport compression that was removed before storage, e.g. `zstd`."
    )
    etag: str | None = Field(..., description="HTTP validator, when the server supplied one.")
    final_url: str | None = Field(
        ..., description="Where it was actually served from after redirects, when different."
    )
    kind: Kind = Field(..., description="What the artifact is.")
    last_modified: str | None = Field(
        ..., description="HTTP validator, when the server supplied one."
    )
    media_type: str = Field(
        ..., description="Media type of the stored bytes (after any transport decompression)."
    )
    retrieved_at: str = Field(
        ...,
        description="When it was retrieved, RFC 3339. Provenance only; never part of any identity.",
    )
    sha256: str = Field(..., description="Full SHA-256 of the stored bytes, lower-case hex.")
    size_bytes: int = Field(..., description="Size of the stored bytes.", ge=0)
    source_uri: str = Field(..., description="Where it was requested from.")


class ArtifactHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str = Field(
        ..., description="What the artifact contains, so a caller can decide whether to read it."
    )
    receipt: Artifact = Field(
        ...,
        description="Exact content identity and this acquisition's provenance. Pass receipt.artifact_id\nto read_artifact; repeated bytes may have different acquisition receipts.",
    )
    uri: str = Field(
        ...,
        description="Always a `library-evidence://` URI -- enforced by [`ArtifactUri`], not only by the schema.",
        pattern="^library-evidence://",
    )


class ArtifactSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heading: str
    kind: Literal["markdown"]


class AspectState(StrEnum):
    available = "available"
    absent = "absent"
    unavailable = "unavailable"
    omitted = "omitted"
    failed = "failed"


class Status(StrEnum):
    documented_available = "documented_available"
    project_availability_unverified = "project_availability_unverified"


class ChangeKind(StrEnum):
    added = "added"
    removed = "removed"
    changed = "changed"


class ComponentStatus(BaseModel):
    available: bool = Field(..., description="Whether it can be used right now.")
    detail: str = Field(
        ...,
        description='Why it is unavailable, or what it covers when it is. Never left blank on an absent\ncomponent -- "blocked" must always name its missing prerequisite.',
    )
    name: str = Field(..., description="The component's stable name.")
    version: str | None = Field(
        None, description="The exact version when known, `None` when the component is absent."
    )


class ConfigurationDifference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after: Any
    before: Any
    field: str


class Mode3(StrEnum):
    project = "project"
    upstream = "upstream"
    compare = "compare"
    revision = "revision"


class Context(BaseModel):
    context_id: str = Field(
        ..., description="Derived from release, environment and mode.", pattern="^ctx_[0-9a-f]{64}$"
    )
    environment_id: str = Field(
        ..., description="The environment it is studied in.", pattern="^env_[0-9a-f]{64}$"
    )
    mode: Mode3 = Field(..., description="The research mode.")
    parent_context_id: str | None = Field(
        ...,
        description="The context this one was derived from, if any.",
        pattern="^ctx_[0-9a-f]{64}$",
    )
    release_id: str = Field(
        ..., description="The release under study.", pattern="^rel_[0-9a-f]{64}$"
    )


class DeliveryLimits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    effective_max_bytes: int | None = Field(..., ge=0)
    requested_max_bytes: int | None = Field(..., ge=0)


class DeltaBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cohort_id: str
    contract_id: str
    relation: str
    rows: int = Field(..., ge=0)
    table_id: str
    table_uri: str
    version: int = Field(..., ge=0)


class Deprecated(BaseModel):
    note: str | None = Field(..., description="The note, if given.")
    since: str | None = Field(..., description="The `since` value, if given.")


class DiagnosticCause(StrEnum):
    invalid_input = "invalid_input"
    not_found = "not_found"
    permission_denied = "permission_denied"
    corrupt_state = "corrupt_state"
    io = "io"
    capacity = "capacity"
    deadline = "deadline"
    invalid_plan = "invalid_plan"
    policy_denied = "policy_denied"
    unsupported = "unsupported"
    upstream = "upstream"
    transport = "transport"
    internal = "internal"


class DiscoveryKind(StrEnum):
    features = "features"
    documentation = "documentation"
    release_notes = "release_notes"
    examples = "examples"


class DocsRsMetadata(BaseModel):
    additional_targets: list[str] = Field(..., description="Targets added to the default set.")
    all_features: bool = Field(..., description="Whether all features were enabled.")
    cargo_args: list[str] = Field(
        ..., description="Extra `cargo` arguments; these can change what compiles at all."
    )
    declared: bool = Field(..., description="Whether the manifest declared the table.")
    default_target: str = Field(..., description="The default target.")
    features: list[str] = Field(..., description="Features enabled for the docs build.")
    no_default_features: bool = Field(..., description="Whether default features were disabled.")
    rustc_args: list[str] = Field(
        ..., description="Extra `rustc` arguments; these can change what compiles at all."
    )
    rustdoc_args: list[str] = Field(..., description="Extra `rustdoc` arguments.")
    targets: list[str] | None = Field(
        ...,
        description="Explicit target list, when set; `None` means docs.rs' tier-one default set.",
    )


class Entry(BaseModel):
    display: str = Field(..., description="Display label.")
    name: str = Field(..., description="Object or label, including spaces.")
    priority: int = Field(..., description="Upstream priority, not a confidence value.")
    role: str = Field(..., description="Domain and role, e.g. py:class or std:label.")
    uri: str = Field(
        ..., description="Resolved document URI; core fetch policy must still approve it."
    )


class Resolution(StrEnum):
    unspecified = "unspecified"
    declared = "declared"
    resolved = "resolved"
    verified = "verified"


class Environment(BaseModel):
    default_features: bool | None = Field(
        ..., description="Whether default features are enabled. `None` when unspecified."
    )
    environment_id: str = Field(
        ..., description="Derived from every other field.", pattern="^env_[0-9a-f]{64}$"
    )
    features: list[str] = Field(
        ..., description="Enabled features or extras, sorted and deduplicated."
    )
    features_known: bool = Field(
        ..., description="Whether an empty feature selection was explicitly supplied."
    )
    lock_digest: str | None = Field(
        ..., description="Digest of the dependency lock, when one was supplied."
    )
    resolution: Resolution = Field(..., description="How much of this environment is known.")
    target: str | None = Field(..., description="Target triple or platform tag, when known.")
    toolchain: str | None = Field(..., description="Compiler or interpreter identity, when known.")


class Code(StrEnum):
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    AMBIGUOUS_PACKAGE = "AMBIGUOUS_PACKAGE"
    ARTIFACT_UNAVAILABLE = "ARTIFACT_UNAVAILABLE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    ENVIRONMENT_UNRESOLVED = "ENVIRONMENT_UNRESOLVED"
    ENVIRONMENT_MISMATCH = "ENVIRONMENT_MISMATCH"
    POLICY_DENIED = "POLICY_DENIED"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    INVALID_CURSOR = "INVALID_CURSOR"
    QUERY_FAILED = "QUERY_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class EvidenceCounters(BaseModel):
    errors: int = Field(..., description="Envelopes answered `error`.", ge=0)
    gaps: int = Field(
        ..., description="Answers that named at least one gap in `coverage.missing`.", ge=0
    )
    ok: int = Field(..., description="Envelopes answered `ok`.", ge=0)
    partial: int = Field(..., description="Envelopes answered `partial`.", ge=0)
    pending: int = Field(
        ..., description="Envelopes answered `pending`, having handed back a job.", ge=0
    )
    requests: int = Field(..., description="Requests dispatched, of every method.", ge=0)
    response_bytes: int = Field(
        ...,
        description='Response bytes produced, after budget enforcement.\n\n"Produced", not "written": a JSON-RPC *notification* is dispatched and answered with\nnothing, and its answer is measured here anyway. The work happened and the bytes were\nbuilt; excluding them would make this number disagree with `requests` for no reason a\nreader could see.',
        ge=0,
    )


class Kind3(StrEnum):
    api_signature = "api_signature"
    doc_text = "doc_text"
    feature_definition = "feature_definition"
    readme_section = "readme_section"
    changelog_section = "changelog_section"
    example = "example"
    source_excerpt = "source_excerpt"


class SourceVersionMatch(Enum):
    exact = "exact"
    compatible_claimed = "compatible_claimed"
    mismatched = "mismatched"
    unknown = "unknown"
    NoneType_None = None


class EvidenceFragment(BaseModel):
    artifact_id: str = Field(..., description="The artifact it was read from.")
    evidence_class: EvidenceClass = Field(..., description="Which epistemic class it belongs to.")
    fragment_id: str = Field(..., description="Content-derived identity.")
    kind: Kind3 = Field(..., description="What kind of text this is.")
    locator: dict[str, Any] = Field(
        ..., description="Position within the artifact, as a JSON object."
    )
    producer: str = Field(..., description="Which producer emitted it.")
    producer_version: str = Field(..., description="The producer's exact version.")
    source_uri: str | None = Field(
        ...,
        description="This fragment's acquisition locator, not the blob's first retrieval locator.",
    )
    source_version_match: SourceVersionMatch | None = Field(
        ...,
        description="Source-specific version match, overriding the release default for mutable docs.",
    )
    subject: str = Field(
        ..., description="What it is about: a symbol path, a feature name, a heading."
    )
    text: str = Field(..., description="The text.")


class IndexedEnum(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"
    distribution_source = "distribution_source"
    stubs = "stubs"
    inventory = "inventory"
    runtime_api = "runtime_api"
    semantic_queries = "semantic_queries"
    usage_probes = "usage_probes"


class MissingEnum(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"
    distribution_source = "distribution_source"
    stubs = "stubs"
    inventory = "inventory"
    runtime_api = "runtime_api"
    semantic_queries = "semantic_queries"
    usage_probes = "usage_probes"


class ExecutionOutcome(StrEnum):
    results = "results"
    empty = "empty"
    unsupported = "unsupported"
    unresolved = "unresolved"
    incomplete = "incomplete"
    failed = "failed"
    cancelled = "cancelled"


class ExecutionPrerequisite(StrEnum):
    enabled_profile = "enabled_profile"
    immutable_image = "immutable_image"
    qualification = "qualification"
    cleanup = "cleanup"


class Ecosystem(StrEnum):
    rust = "rust"
    python = "python"


class ExecutionTarget2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["external"]
    limitation: str
    path: str
    scope: str


class ExecutionTarget3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["unresolved"]
    limitation: str


class SourceVersionMatch3(StrEnum):
    exact = "exact"
    compatible_claimed = "compatible_claimed"
    mismatched = "mismatched"
    unknown = "unknown"


class FetchCounters(BaseModel):
    failures: int = Field(
        ..., description="Requests that failed before producing a response.", ge=0
    )
    fetched_bytes: int = Field(
        ..., description="Body bytes actually transferred, excluding reused cache bytes.", ge=0
    )
    hits: int = Field(
        ...,
        description="Requests answered from the service cache without contacting the origin.",
        ge=0,
    )
    misses: int = Field(..., description="Requests that transferred a body from the origin.", ge=0)
    revalidated: int = Field(
        ..., description="Requests where validators matched and the origin returned `304`.", ge=0
    )


class Kind4(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"
    distribution_source = "distribution_source"
    stubs = "stubs"
    inventory = "inventory"
    runtime_api = "runtime_api"
    semantic_queries = "semantic_queries"
    usage_probes = "usage_probes"


class Reason(StrEnum):
    hosted_json_missing = "hosted_json_missing"
    hosted_json_unsupported = "hosted_json_unsupported"
    upstream_unavailable = "upstream_unavailable"
    policy_denied = "policy_denied"
    extraction_failed = "extraction_failed"
    not_attempted = "not_attempted"


class State2(StrEnum):
    available = "available"
    missing = "missing"
    unsupported = "unsupported"
    not_attempted = "not_attempted"


class SupportedFormat(RootModel[int]):
    root: int = Field(..., ge=0)


class HostedJsonReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    declared_crate_version: str | None = Field(
        ..., description="`crate_version` as the JSON itself declares it, when available."
    )
    format_version: int | None = Field(
        ..., description="The format version the payload declared, when one was read.", ge=0
    )
    state: State2 = Field(..., description="What was found.")
    supported_formats: list[SupportedFormat] = Field(
        ..., description="The format versions this build can interpret."
    )
    target: str = Field(..., description="The target the JSON was requested for.")
    url: str = Field(..., description="The URL that was asked.")


class InspectionAspect(StrEnum):
    signature = "signature"
    availability = "availability"
    relationships = "relationships"
    documentation = "documentation"
    examples = "examples"
    source = "source"
    semantics = "semantics"
    runtime = "runtime"
    children = "children"
    members = "members"


class Kind5(StrEnum):
    module = "module"
    struct = "struct"
    class_ = "class"
    attribute = "attribute"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    extern_type = "extern_type"
    import_ = "import"


class InspectionCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition_id: str
    kind: Kind5 = Field(
        ...,
        description="What kind of item a symbol is.\n\nThe values are, in order: `module`, `struct`, `union`, `enum`, `variant`, `struct_field`,\n`trait`, `trait_alias`, `type_alias`, `function`, `method`, `constant`, `static`, `macro`,\n`proc_macro`, `assoc_type`, `assoc_const`, `primitive`, `extern_crate`, `import`.",
    )
    path: str
    qualifier: str | None


class State3(StrEnum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancel_requested = "cancel_requested"
    cancelled = "cancelled"


class Outcome(StrEnum):
    ok = "ok"
    partial = "partial"
    pending = "pending"
    error = "error"


class Locator1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["artifact"]


class Locator2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: int = Field(..., ge=0)
    file: str | None
    kind: Literal["lines"]
    start: int = Field(..., ge=0)


class Locator3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: int = Field(..., ge=0)
    kind: Literal["bytes"]
    start: int = Field(..., ge=0)


class Locator4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["archive_member"]
    path: str


class Locator5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    heading: str
    kind: Literal["heading"]
    ordinal: int = Field(..., ge=0)


class Locator6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item: str
    kind: Literal["producer_item"]
    producer: str


class Locator7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item: int = Field(..., ge=0)
    kind: Literal["rustdoc_item"]
    reported_file: str | None
    reported_line: int | None = Field(..., ge=0)


class Locator8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    declaration: str
    file: str
    kind: Literal["python_declaration"]
    line: int | None = Field(..., ge=0)
    origin: ApiOrigin
    overload: int | None = Field(..., ge=0)


class Locator9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    key: str
    kind: Literal["manifest_key"]
    table: str


class Locator10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    heading: str
    kind: Literal["markdown_section"]
    line: int = Field(..., ge=0)


class Locator11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    kind: Literal["source_start"]
    line: int = Field(..., ge=0)


class Locator12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inventory_version: str
    kind: Literal["sphinx_inventory"]
    project: str
    role: str
    uri: str


class Locator13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inventory_version: str
    kind: Literal["web_document"]
    uri: str


class Locator14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: str
    kind: Literal["extension"]
    value: Any
    version: str


class Locator(
    RootModel[
        Locator1
        | Locator2
        | Locator3
        | Locator4
        | Locator5
        | Locator6
        | Locator7
        | Locator8
        | Locator9
        | Locator10
        | Locator11
        | Locator12
        | Locator13
        | Locator14
    ]
):
    root: (
        Locator1
        | Locator2
        | Locator3
        | Locator4
        | Locator5
        | Locator6
        | Locator7
        | Locator8
        | Locator9
        | Locator10
        | Locator11
        | Locator12
        | Locator13
        | Locator14
    ) = Field(
        ...,
        description="Typed artifact coordinates. Open producer payloads have an explicit versioned boundary.",
    )


class LspMetrics(BaseModel):
    evicted: int = Field(
        ...,
        description="Sessions shut down to stay within the configured bound, or after idling out.",
        ge=0,
    )
    reused: int = Field(
        ..., description="Queries answered by a session that was already warm.", ge=0
    )
    started: int = Field(
        ..., description="Sessions actually started, each one a language-server process.", ge=0
    )
    warm: int = Field(..., description="Sessions warm right now.", ge=0)


class MatchCount1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["exact"]
    value: int = Field(..., ge=0)


class MatchCount2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lower_bound"]
    value: int = Field(..., ge=0)


class MatchCount3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["unknown"]


class MatchCount(RootModel[MatchCount1 | MatchCount2 | MatchCount3]):
    root: MatchCount1 | MatchCount2 | MatchCount3 = Field(
        ..., description="Count meaning is explicit; absence is never silently represented as zero."
    )


class CountsByKind(RootModel[int]):
    root: int = Field(..., ge=0)


class NativeQueryCounters(BaseModel):
    admitted: int = Field(
        ...,
        description="Queries currently holding a shared admission permit, including stream writers.",
        ge=0,
    )
    completed: int = Field(..., ge=0)
    concurrency_limit: int = Field(..., ge=0)
    diagnostic_observations_dropped: int = Field(..., ge=0)
    effective_native_settings: dict[str, str] = Field(
        ..., description="The read-only values consumed by native source construction."
    )
    elapsed_micros: int = Field(
        ...,
        description="Sum of elapsed execution durations, which overlap for concurrent queries.",
        ge=0,
    )
    executions: int = Field(
        ...,
        description="Completed or interrupted physical executions recorded since startup.",
        ge=0,
    )
    incomplete: int = Field(
        ...,
        description="Failed, cancelled or dropped executions, including partial operator counters.",
        ge=0,
    )
    managed_memory_limit_bytes: int = Field(
        ...,
        description="Configured managed memory ceiling; external parser/scan allocations are separate.",
        ge=0,
    )
    managed_memory_peak_bytes: int = Field(
        ...,
        description="Shared-runtime maximum since startup; never reset or attributed to one query.",
        ge=0,
    )
    managed_memory_reserved_bytes: int = Field(
        ..., description="Current shared-runtime managed reservations, not process RSS.", ge=0
    )
    metadata_cache_limit_bytes: int = Field(..., ge=0)
    planning_micros: int = Field(
        ..., description="Sum of observed planning time across recorded executions.", ge=0
    )
    spill_limit_bytes: int = Field(..., ge=0)


class ObservationOrigin(StrEnum):
    source = "source"
    stub = "stub"


class ObservedConfiguration(BaseModel):
    all_features: bool = Field(..., description="Whether all features were enabled.")
    features: list[str] = Field(
        ..., description="Features the docs build enabled, as the manifest declared them."
    )
    format_version: int = Field(..., description="The rustdoc JSON format version.", ge=0)
    no_default_features: bool = Field(..., description="Whether default features were disabled.")
    source: str = Field(..., description="Where the configuration was read from.")
    target: str = Field(..., description="The target the JSON itself declares.")


class OverviewChild(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deprecated: bool = Field(..., description="Whether deprecated.")
    doc_summary: str | None = Field(..., description="Summary, when documented.")
    is_reexport: bool = Field(
        ..., description="Whether this path re-exports a definition elsewhere."
    )
    kind: Kind5 = Field(..., description="Kind.")
    path: str = Field(..., description="Public path.")


class Page(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: MatchCount = Field(
        ...,
        description="Explicit exact, lower-bound or unknown count; never infer absence from a page.",
    )
    has_more: bool = Field(
        ..., description="Whether another nonempty page can be requested with next_cursor."
    )
    next_cursor: str | None = Field(
        ..., description="Opaque cursor for the next page, or `null` at the end."
    )
    returned: int = Field(..., description="How many entries this page carries.", ge=0)


class PlannedFallback(BaseModel):
    enabled: bool = Field(..., description="Whether configuration currently enables that profile.")
    next_action: str = Field(..., description="What a caller or operator would do to make it run.")
    producer: str = Field(..., description="Producer name.")
    profile: str = Field(..., description="The execution profile it needs.")


class ProcessAuthority1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    effect_id: str
    environment_id: str | None
    grant_id: str
    kind: Literal["command"]
    snapshot_id: str | None


class ProcessAuthority2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition_id: str
    kind: Literal["qualification"]


class ProcessAuthority(RootModel[ProcessAuthority1 | ProcessAuthority2]):
    root: ProcessAuthority1 | ProcessAuthority2 = Field(
        ..., description="Raw bounded process observation, independent of what a probe establishes."
    )


class End(StrEnum):
    exited = "exited"
    deadline = "deadline"
    output_limit = "output_limit"
    cancelled = "cancelled"


class ProcessObservation(BaseModel):
    authority: ProcessAuthority
    cleanup_confirmed: bool
    command: list[str]
    end: End
    exit_code: int | None
    finished_at: str
    image_id: str
    operation_id: str
    started_at: str
    stderr: str
    stdout: str


class Outcome1(StrEnum):
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    skipped = "skipped"


class Publicness(BaseModel):
    declared_exports: list[str] = Field(..., description="Literal __all__ entries.")
    docstring: bool = Field(
        ..., description="A docstring exists; absence does not prove private API."
    )
    exported: bool | None = Field(
        ..., description="Membership in a statically resolved __all__, when known."
    )
    reexport: bool = Field(..., description="This is a reexport declaration.")
    underscore: bool = Field(
        ..., description="Underscore naming convention, not a privacy verdict."
    )
    unresolved_exports: list[str] = Field(
        ..., description="Export expressions not statically reduced to literals."
    )


class PythonDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alias_target: str | None
    bases: list[str]
    overloads: list[str]
    publicness: Publicness


class RecoveryAction7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    arguments: dict[str, Any]
    kind: Literal["call_tool"]
    tool: str


class RecoveryAction9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["retry_after"]
    milliseconds: int = Field(..., ge=0)


class RecoveryAction10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["change_request"]
    reason: str


class RecoveryAction11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["operator_setup"]
    reason: str


class RecoveryAction12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["report_defect"]
    reason: str


class RelationChanges(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inserted: int = Field(..., ge=0)
    relation: str
    removed: int = Field(..., ge=0)
    updated: int = Field(..., ge=0)


class Relation(StrEnum):
    reexports = "reexports"
    implements = "implements"
    inherits = "inherits"
    member_of = "member_of"
    documents = "documents"
    returns = "returns"
    accepts = "accepts"


class ReleaseLinks(BaseModel):
    documentation: str | None = Field(..., description="Documentation site.")
    homepage: str | None = Field(..., description="Project homepage.")
    repository: str | None = Field(..., description="Source repository.")


class RequestedConfiguration(BaseModel):
    default_features: bool | None = Field(
        ..., description="Whether default features are enabled, when declared."
    )
    features: list[str] | None = Field(
        ..., description="Features the project enables, when declared."
    )
    target: str | None = Field(..., description="The project's target, when declared.")


class ResultSectionName(StrEnum):
    coverage = "coverage"
    signature = "signature"
    changes = "changes"
    aspects = "aspects"
    data = "data"


class RuntimeObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attributes: list[str]
    docstring: str | None
    limitations: list[str]
    module: str
    outcome: ExecutionOutcome
    selection: list[str]
    signature: str | None
    type_name: str | None = Field(
        ..., description="The actual Python type's qualified name; not a static SymbolKind claim."
    )


class SchemaCompatibility(BaseModel):
    accepts: list[str] = Field(..., description="Every version this daemon can accept.")
    emits: str = Field(..., description="The version emitted on every response.")


class Scope(StrEnum):
    api = "api"
    docs = "docs"
    configuration = "configuration"
    release_notes = "release_notes"
    examples = "examples"
    relationships = "relationships"


class Kind7(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"
    distribution_source = "distribution_source"
    stubs = "stubs"
    inventory = "inventory"
    runtime_api = "runtime_api"
    semantic_queries = "semantic_queries"
    usage_probes = "usage_probes"


class ScopeState(StrEnum):
    indexed = "indexed"
    partial = "partial"
    missing = "missing"
    unknown = "unknown"


class ScoreFactor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Factor name.")
    points: int = Field(..., description="Points contributed.", ge=0)


class FragmentKind(Enum):
    api_signature = "api_signature"
    doc_text = "doc_text"
    feature_definition = "feature_definition"
    readme_section = "readme_section"
    changelog_section = "changelog_section"
    example = "example"
    source_excerpt = "source_excerpt"
    NoneType_None = None


class Hit(StrEnum):
    symbol = "symbol"
    fragment = "fragment"


class SymbolKind(Enum):
    module = "module"
    struct = "struct"
    class_ = "class"
    attribute = "attribute"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    extern_type = "extern_type"
    import_ = "import"
    NoneType_None = None


class SearchHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    deprecated: bool = Field(..., description="Whether the symbol is deprecated.")
    evidence_id: str = Field(..., description="The evidence entry this hit is cited by.")
    excerpt: str = Field(..., description="Bounded excerpt.")
    factors: list[ScoreFactor] = Field(..., description="The factors behind the score.")
    fragment_kind: FragmentKind | None = Field(..., description="Fragment kind, for fragment hits.")
    hit: Hit = Field(..., description="Symbol or fragment.")
    path: str | None = Field(..., description="Symbol path, for symbol hits.")
    score: int = Field(..., description="Total score.", ge=0)
    signature: str | None = Field(..., description="Rendered signature, for symbol hits.")
    subject: str | None = Field(..., description="Fragment subject, for fragment hits.")
    symbol_kind: SymbolKind | None = Field(..., description="Symbol kind, for symbol hits.")


class SemanticMethod(StrEnum):
    hover = "hover"
    definition = "definition"
    implementation = "implementation"
    references = "references"
    diagnostics = "diagnostics"


class SingleFlightCounts(BaseModel):
    inflight: int = Field(..., description="Distinct pieces of work running right now.", ge=0)
    shared: int = Field(
        ..., description="Callers that attached to a run someone else started.", ge=0
    )
    started: int = Field(..., description="Producer runs this process actually started.", ge=0)
    total_millis: int = Field(
        ...,
        description="Total wall time spent inside producer work, across every started run.\n\nSummed rather than averaged: a mean loses the one run that took a minute, and §14.3 wants\na diagnostic, not a statistic. Divide by `started` if a mean is what you want.",
        ge=0,
    )


class SnapshotCounts(BaseModel):
    definitions: int = Field(..., description="Distinct definitions.", ge=0)
    fragments: int = Field(..., description="Fragments.", ge=0)
    producer_items: int = Field(
        ...,
        description="Items the producer saw in total, including those not surfaced as symbols.",
        ge=0,
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    relationships: int = Field(..., description="Typed edges.", ge=0)
    symbols: int = Field(..., description="Public paths.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )


class SnapshotDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str = Field(
        ...,
        description="Binds a release to an environment and a research mode.",
        pattern="^ctx_[0-9a-f]{64}$",
    )
    crate_name: str
    crate_version: str | None
    ecosystem: Ecosystem = Field(
        ...,
        description="Which package ecosystem a release belongs to.\n\nThe values are, in order: `rust`, `python`. No variant carries a doc comment -- see the\nmodule docs in [`crate::wire`].",
    )
    environment_id: str = Field(
        ...,
        description="Identifies the declared or resolved environment.",
        pattern="^env_[0-9a-f]{64}$",
    )
    normalizer_version: str
    observed_configuration: ObservedConfiguration | None
    producer_items: int = Field(..., ge=0)
    release_id: str = Field(
        ...,
        description="Identifies the actual library release: ecosystem, registry, package, exact version and\nthe selected artifact digest.",
        pattern="^rel_[0-9a-f]{64}$",
    )
    symbol_package: str


class SnapshotSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    counts: SnapshotCounts = Field(..., description="Counts.")
    normalizer_version: str = Field(..., description="Normalizer version that produced it.")
    published_at: str = Field(..., description="Publication time.")
    snapshot_id: str = Field(..., description="The snapshot identity.")


class SourceWindowKind(StrEnum):
    recorded_line_window = "recorded_line_window"


class SubjectRef7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["symbol"]
    symbol_id: str


class SubjectRef8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition_id: str
    kind: Literal["definition"]


class SubjectRef9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["library"]
    release_id: str


class SubjectRef10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["feature"]
    name: str


class SubjectRef11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    heading: str
    kind: Literal["document"]


class SubjectRef12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    kind: Literal["example"]
    path: str


class SubjectRef(
    RootModel[SubjectRef7 | SubjectRef8 | SubjectRef9 | SubjectRef10 | SubjectRef11 | SubjectRef12]
):
    root: SubjectRef7 | SubjectRef8 | SubjectRef9 | SubjectRef10 | SubjectRef11 | SubjectRef12 = (
        Field(
            ...,
            description="A reference carries its indexing domain. External paths never masquerade as local keys.",
        )
    )


class Kind8(StrEnum):
    module = "module"
    struct = "struct"
    class_ = "class"
    attribute = "attribute"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    extern_type = "extern_type"
    import_ = "import"


class Symbol(BaseModel):
    cfg_hints: list[str] = Field(
        ...,
        description="`cfg`-shaped attribute strings the producer preserved, as declared hints only. Never\na feature predicate: items compiled out are absent, not annotated (§4.3).",
    )
    defined_in_crate: str = Field(..., description="The crate the definition belongs to.")
    definition_id: str = Field(..., description="Identity of the definition this path names.")
    definition_path: str = Field(..., description="The path the item is defined at.")
    deprecated: Deprecated | None = Field(..., description="Deprecation, when marked.")
    doc_summary: str | None = Field(
        ..., description="First paragraph of the documentation, bounded."
    )
    docs: str | None = Field(..., description="Full documentation text.")
    is_reexport: bool = Field(
        ..., description="Whether this path is a re-export of a definition elsewhere."
    )
    kind: Kind8 = Field(..., description="What kind of item this is.")
    name: str = Field(..., description="The last path segment.")
    parent_path: str | None = Field(..., description="The containing path, when any.")
    path: str = Field(..., description="Canonical public path, e.g. `enr_fixture::inner::Widget`.")
    producer_local_id: int = Field(
        ...,
        description="The producer's own item identifier -- local, never a cross-release identity.",
        ge=0,
    )
    qualifier: str | None = Field(
        ..., description="Trait or declaration qualifier included in symbol/definition identity."
    )
    signature: str | None = Field(
        ..., description="Rendered signature, when the producer rendered one."
    )
    span_file: str | None = Field(..., description="Source file as the producer recorded it.")
    span_line: int | None = Field(
        ..., description="1-based source line as the producer recorded it.", ge=0
    )
    symbol_id: str = Field(
        ...,
        description="Identity of this public path: hash of crate, path, kind and (for trait-impl members)\nthe trait.",
    )


class TargetRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["symbol"]
    symbol_id: str


class TargetRef2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    definition_id: str
    kind: Literal["definition"]


class TargetRef3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["external"]
    package: str | None
    path: str


class TargetRef4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["unresolved"]
    path: str


class TargetRef(RootModel[TargetRef1 | TargetRef2 | TargetRef3 | TargetRef4]):
    root: TargetRef1 | TargetRef2 | TargetRef3 | TargetRef4 = Field(
        ..., description="Relationship target domains, including legitimate unresolved targets."
    )


class UpstreamCheck(BaseModel):
    newest_any: str | None = Field(..., description="Newest non-yanked version of any kind.")
    newest_stable: str | None = Field(..., description="Newest non-yanked, non-prerelease version.")
    published_versions: int = Field(
        ..., description="Number of published versions the index listed.", ge=0
    )
    resolved_is_newest_stable: bool = Field(
        ..., description="Whether the resolved version is the newest stable one."
    )


class Mode4(StrEnum):
    compile = "compile"
    typecheck = "typecheck"
    runtime = "runtime"


class UsageProbe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: End
    exit_code: int | None
    mode: Mode4
    snippet_artifact_id: str
    stderr: str
    stdout: str


class Utf8Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byte: int = Field(..., ge=0)
    line: int = Field(..., ge=0)


class Utf8Range(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end: Utf8Position
    start: Utf8Position


class VerificationCounters(BaseModel):
    failed: int = Field(
        ..., description="Probes that ran and failed, which is an observation about the code.", ge=0
    )
    succeeded: int = Field(..., description="Probes that ran and succeeded.", ge=0)
    unresolved: int = Field(
        ...,
        description="Probes that could not be run, which is an observation about the service.",
        ge=0,
    )


class Versions(BaseModel):
    daemon: str = Field(..., description="The daemon crate version.")
    schema_: str = Field(
        ..., alias="schema", description="The wire schema version this build emits."
    )


class WorkerFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str = Field(..., description="Archive-relative file path.")
    module: str = Field(..., description="Qualified module import path.")
    origin: ObservationOrigin = Field(..., description="Whether it is .py or .pyi.")


class LibraryEnrichmentToolData6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(
        ..., description="Namespace subtree that was searched, when requested."
    )
    hits: list[SearchHit] = Field(..., description="The hits on this page.")
    kinds: list[str] = Field(..., description="The evidence families searched.")
    offset: int = Field(..., description="Page offset.", ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    query: str = Field(..., description="The query as asked.")
    scoring: list[ScoreFactor] = Field(..., description="The scoring legend, in rank order.")
    searched: list[str] = Field(..., description="Which sources were searched.")
    tokens: list[str] = Field(..., description="The tokens it was split into.")
    tool: Literal["search_evidence"]


class LibraryEnrichmentToolData8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: Artifact = Field(..., description="The artifact record.")
    content: str = Field(..., description="The slice.")
    content_digest: str = Field(..., description="SHA-256 of the slice bytes.")
    encoding: Encoding = Field(..., description="How `content` is encoded.")
    end: int = Field(..., description="One past the last byte offset of the slice.", ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    remaining: int = Field(..., description="Bytes after `end`.", ge=0)
    section: str | None = Field(..., description="The section that was selected, when one was.")
    start: int = Field(..., description="First byte offset of the slice.", ge=0)
    tool: Literal["read_artifact"]
    total: int = Field(..., description="Total artifact size.", ge=0)


class AlternativeValue2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactHandle
    mode: Literal["artifact"]
    sha256: str
    size_bytes: int = Field(..., ge=0)


class AlternativeValue(RootModel[AlternativeValue1 | AlternativeValue2]):
    root: AlternativeValue1 | AlternativeValue2 = Field(
        ...,
        description="Complete value delivery, independent of the alternative's fact provenance.",
    )


class ApiPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cfg_hints: list[str]
    declared_kind: DeclaredKind = Field(
        ...,
        description="What kind of item a symbol is.\n\nThe values are, in order: `module`, `struct`, `union`, `enum`, `variant`, `struct_field`,\n`trait`, `trait_alias`, `type_alias`, `function`, `method`, `constant`, `static`, `macro`,\n`proc_macro`, `assoc_type`, `assoc_const`, `primitive`, `extern_crate`, `import`.",
    )
    deprecated: Deprecated | None
    doc_summary: str | None
    docs: str | None
    python: PythonDetails | None
    signature: str | None


class ArtifactSection8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["result"]
    name: ResultSectionName


class ArtifactSection6(RootModel[ArtifactSection | ArtifactSection8]):
    root: ArtifactSection | ArtifactSection8 = Field(
        ..., description="A result projection is distinct from a Markdown heading selection."
    )


class ArtifactSliceData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: Artifact = Field(..., description="The artifact record.")
    content: str = Field(..., description="The slice.")
    content_digest: str = Field(..., description="SHA-256 of the slice bytes.")
    encoding: Encoding = Field(..., description="How `content` is encoded.")
    end: int = Field(..., description="One past the last byte offset of the slice.", ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    remaining: int = Field(..., description="Bytes after `end`.", ge=0)
    section: str | None = Field(..., description="The section that was selected, when one was.")
    start: int = Field(..., description="First byte offset of the slice.", ge=0)
    total: int = Field(..., description="Total artifact size.", ge=0)


class Availability(BaseModel):
    notes: list[str] = Field(..., description="Why the status is what it is, in prose.")
    observed_configuration: ObservedConfiguration = Field(
        ..., description="The documented build's configuration."
    )
    requested_configuration: RequestedConfiguration = Field(
        ..., description="The caller's declared configuration."
    )
    status: Status = Field(..., description="The strongest honest claim.")


class DeliveryDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limits: DeliveryLimits
    mode: Literal["inline"]


class Distribution(BaseModel):
    entry_points: str | None = Field(
        ..., description="Raw entry-point declarations; nothing is imported."
    )
    filename: str = Field(..., description="Selected immutable artifact filename.")
    files: list[WorkerFile] = Field(..., description="Source and stub file mappings.")
    import_roots: list[str] = Field(..., description="Import roots derived from archive layout.")
    inventory: list[Entry] = Field(
        ..., description="Documentation navigation, separately versioned from distribution facts."
    )
    metadata: dict[str, list[str]] = Field(
        ..., description="Selected METADATA/PKG-INFO fields, preserving repeated headers."
    )
    name: str | None = Field(
        ...,
        description="Observed built-metadata Name header, distinct from source/import identity; null if absent.",
    )
    native_files: list[str] = Field(
        ..., description="Native extension paths unavailable to static AST extraction."
    )
    sha256: str = Field(..., description="Selected artifact digest.")
    source_root: str = Field(..., description="Archive-relative source root, empty for wheels.")
    typed_markers: list[str] = Field(
        ..., description="py.typed marker paths (including partial stub markers)."
    )
    version: str | None = Field(
        ..., description="Observed built-metadata Version header; null when no header was produced."
    )
    worker_artifact_id: str | None = Field(
        ..., description="Exact worker output artifact when extraction ran."
    )


class EvidenceManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    components: dict[str, str]
    counts: SnapshotCounts
    indexed: list[IndexedEnum]
    metadata: SnapshotDescriptor
    missing: list[MissingEnum]
    published_at: str
    schema_version: str
    snapshot_id: str = Field(
        ...,
        description="Names one immutable set of evidence available for a context.",
        pattern="^snap_[0-9a-f]{64}$",
    )
    tables: list[DeltaBinding]


class ExecutionDiagnostic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str | None
    message: str
    range: Utf8Range
    severity: int | None = Field(
        ..., description="LSP severity 1–4, or absent when the server did not supply one.", ge=0
    )
    source: str | None


class ExecutionPayload2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["runtime_object"]
    value: RuntimeObject


class ExecutionPayload3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["usage_probe"]
    value: UsageProbe


class ExecutionTarget1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    kind: Literal["artifact"]
    range: Utf8Range


class ExecutionTarget(RootModel[ExecutionTarget1 | ExecutionTarget2 | ExecutionTarget3]):
    root: ExecutionTarget1 | ExecutionTarget2 | ExecutionTarget3


class FactSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    evidence_class: EvidenceClass = Field(
        ...,
        description='The six epistemic classes (blueprint §6.2).\n\nThese are categories, not a confidence scale. An API signature can be `compiler_derived`\nwhile "this replaces our orchestration layer" is `agent_inferred`, and the two never merge.\n\nThe values are, in order: `declared`, `statically_extracted`, `compiler_derived`,\n`typechecker_observed`, `runtime_observed`, `agent_inferred`.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).',
    )
    extractor: str = Field(
        ...,
        description="Component within the producing job (for example public-api inside normalization).",
    )
    extractor_version: str
    locator: Locator
    producer_binding_id: str
    source_uri: str | None
    source_version_match: SourceVersionMatch3 = Field(
        ...,
        description="How well the evidence's source version matches the version that was asked about.\n\nThe values are, in order: `exact`, `compatible_claimed`, `mismatched`, `unknown`.\n`compatible_claimed` is a claim by the source, not a verified fact.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).",
    )


class Gap(BaseModel):
    detail: str = Field(
        ..., description="Human-readable detail, e.g. the format version that was refused."
    )
    kind: Kind4 = Field(..., description="What is missing.")
    planned_fallback: PlannedFallback | None = Field(
        ..., description="The producer and profile that would supply it, when one exists."
    )
    reason: Reason = Field(..., description="Why.")


class Health(BaseModel):
    cache_ready: bool = Field(..., description="Whether the evidence store is open and writable.")
    data_root: str | None = Field(
        None, description="The data root in use, when a store is open. Absent otherwise."
    )
    evidence: EvidenceCounters = Field(
        ..., description="What this process has answered, and how completely."
    )
    fetch: FetchCounters = Field(
        ..., description="HTTP cache outcomes and transferred bytes since this process started."
    )
    lsp: LspMetrics = Field(
        ...,
        description='Language-server starts, reuses and evictions in this daemon process.\n\nPublished because gate C17 -- "inspection does not start an LSP unnecessarily" -- is only\ncheckable against a counter. A caller reading `started` before and after a signature-only\ninspection can see for itself that nothing was started. Blueprint §14.3 asks for the same\nnumbers as operational metrics.',
    )
    native_queries: NativeQueryCounters | None = Field(
        ...,
        description="Native query counters and configured limits, absent when no runtime is open.",
    )
    queued_jobs: int = Field(..., description="Jobs currently queued.", ge=0)
    running_jobs: int = Field(..., description="Jobs currently running.", ge=0)
    single_flight: SingleFlightCounts = Field(
        ...,
        description="Producer runs started, and callers served by a run someone else started (§8.2, C04).",
    )
    uptime_seconds: int = Field(
        ...,
        description="How long this process has been up, in seconds.\n\nEvery counter beside it is scoped to that window. Without this an operator reading\n`fetch.misses = 3` cannot tell a quiet hour from a daemon that restarted a minute ago.",
        ge=0,
    )
    verification: VerificationCounters = Field(..., description="How verification probes finished.")


class NamespaceFacet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    children: list[OverviewChild] = Field(
        ..., description="A bounded sample of direct children, definitions counted once."
    )
    counts_by_kind: dict[str, CountsByKind] = Field(
        ..., description="Distinct definitions directly under this module, by kind."
    )
    doc_summary: str | None = Field(..., description="First paragraph of the module docs.")
    path: str = Field(..., description="The module path.")
    truncated_children: int = Field(..., description="Children beyond the sample.", ge=0)


class ProducerRun(BaseModel):
    attempt_id: str = Field(
        ...,
        description="Unique execution-attempt identity, excluded from semantic content and reuse keys.",
    )
    config_digest: str = Field(
        ..., description="Digest of the normalized options the run was configured with."
    )
    finished_at: str = Field(..., description="RFC 3339 finish time. Provenance only.")
    gaps: list[Gap] = Field(
        ..., description="Evidence the run was expected to yield and did not, each with a reason."
    )
    inputs: dict[str, str] = Field(..., description="Input artifact digests by role.")
    log: str | None = Field(..., description="Bounded log text, when any was kept.")
    outcome: Outcome1 = Field(..., description="How it ended.")
    producer: str = Field(..., description="Producer name.")
    producer_version: str = Field(..., description="Exact producer version.")
    profile: Profile = Field(..., description="The execution profile the run was performed under.")
    started_at: str = Field(..., description="RFC 3339 start time. Provenance only.")


class RecoveryAction8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    cursor: str | None
    kind: Literal["read_artifact"]
    section: ArtifactSection6 | None


class RecoveryAction(
    RootModel[
        RecoveryAction7
        | RecoveryAction8
        | RecoveryAction9
        | RecoveryAction10
        | RecoveryAction11
        | RecoveryAction12
    ]
):
    root: (
        RecoveryAction7
        | RecoveryAction8
        | RecoveryAction9
        | RecoveryAction10
        | RecoveryAction11
        | RecoveryAction12
    ) = Field(
        ..., description="An actionable follow-up, never an instruction to execute automatically."
    )


class RelationshipObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    qualifier: str | None
    relation: Relation = Field(
        ...,
        description="Typed relations between symbols (§6.1).\n\nThe values are, in order: `reexports`, `implements`, `member_of`, `documents`, `returns`,\n`accepts`.",
    )
    relationship_id: str
    source: FactSource
    subject: SubjectRef
    target: TargetRef


class Release(BaseModel):
    artifact_digest: str | None = Field(
        ...,
        description="The registry checksum of the selected artifact, when the registry publishes one.",
    )
    ecosystem: Ecosystem = Field(..., description="Which ecosystem.")
    lib_name: str | None = Field(
        ..., description="The library target name declared in the manifest, when known."
    )
    license: str | None = Field(..., description="SPDX licence expression as published.")
    links: ReleaseLinks = Field(..., description="Registry-published links.")
    package: str = Field(..., description="The normalized package name as the registry knows it.")
    published_at: str | None = Field(
        ..., description="Publication time as the registry records it."
    )
    registry: str = Field(
        ..., description="The registry the package was resolved against, e.g. `crates.io`."
    )
    release_id: str = Field(
        ...,
        description="Derived from `key`; never set independently.",
        pattern="^rel_[0-9a-f]{64}$",
    )
    root_module: str | None = Field(
        ..., description="The root module name as it appears in `use` paths, when known."
    )
    rust_version: str | None = Field(
        ..., description="Minimum supported Rust version as published."
    )
    version: str = Field(
        ..., description="The exact version, or an immutable revision for `revision` mode."
    )
    yanked: bool = Field(..., description="Whether the registry has yanked this version.")


class ResolveData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answered_from_cache: bool = Field(
        ...,
        description="Whether this answer was replayed from a recorded resolution rather than fetched.",
    )
    artifacts: list[Artifact] = Field(
        ..., description="Every artifact this resolution stored or reused."
    )
    context: Context = Field(..., description="The context identity every later call takes.")
    environment: Environment = Field(
        ..., description="The environment the context binds, with its resolution status."
    )
    gaps: list[Gap] = Field(
        ...,
        description="Expected evidence that is absent, each with a reason and a planned fallback.",
    )
    hosted_rustdoc_json: HostedJsonReport | None = Field(
        ..., description="Hosted rustdoc JSON availability."
    )
    observed_configuration: DocsRsMetadata | None = Field(
        ...,
        description="The maintainer's docs.rs build configuration, read from the crate manifest.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Provenance for each producer that ran."
    )
    python: Distribution | None = Field(
        ..., description="Distribution metadata and file inventory, only for Python."
    )
    release: Release = Field(
        ...,
        description="The release that was resolved. Its version is the one asked for, never an upgrade.",
    )
    snapshot: SnapshotSummary | None = Field(
        ...,
        description="The snapshot published from this resolution, when normalization succeeded.",
    )
    upstream: UpstreamCheck | None = Field(
        ...,
        description="What the registry said about newer releases, kept apart from the resolution.",
    )


class ResultSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    name: ResultSectionName


class ScopeAssessment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind7 = Field(
        ...,
        description="The kinds of evidence a producer can require or yield, and that `coverage.indexed` and\n`coverage.missing` name.\n\nThe values are, in order: `registry_metadata`, `crate_source`,\n`documentation_build_config`, `hosted_rustdoc_json`, `public_api`, `documentation`,\n`examples`, `release_notes`, `source_excerpts`.",
    )
    snapshot_id: str
    state: ScopeState
    subject: SubjectRef
    witness_id: str | None = Field(
        ...,
        description="A qualified fact establishing the selected state. Historical attempts remain retained.",
    )


class SearchData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(
        ..., description="Namespace subtree that was searched, when requested."
    )
    hits: list[SearchHit] = Field(..., description="The hits on this page.")
    kinds: list[str] = Field(..., description="The evidence families searched.")
    offset: int = Field(..., description="Page offset.", ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    query: str = Field(..., description="The query as asked.")
    scoring: list[ScoreFactor] = Field(..., description="The scoring legend, in rank order.")
    searched: list[str] = Field(..., description="Which sources were searched.")
    tokens: list[str] = Field(..., description="The tokens it was split into.")


class SemanticQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anchor_symbol_id: str | None
    diagnostics: list[ExecutionDiagnostic]
    document_artifact_id: str
    hover: str | None
    limitations: list[str]
    locations: list[ExecutionTarget]
    method: SemanticMethod
    outcome: ExecutionOutcome
    position: Utf8Position | None
    server: str


class SourceExcerpt(BaseModel):
    end_line: int = Field(..., description="Last line included, 1-based.", ge=0)
    path: str = Field(..., description="The file, relative to the crate root.")
    start_line: int = Field(..., description="First line included, 1-based.", ge=0)
    text: str = Field(..., description="The text.")
    truncated: bool = Field(..., description="Whether the file had more lines after `end_line`.")
    window_kind: SourceWindowKind


class VerificationData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    derived_context: Context | None
    derived_snapshot_id: str | None
    environment: Environment | None
    evidence_class: EvidenceClass = Field(
        ...,
        description='The six epistemic classes (blueprint §6.2).\n\nThese are categories, not a confidence scale. An API signature can be `compiler_derived`\nwhile "this replaces our orchestration layer" is `agent_inferred`, and the two never merge.\n\nThe values are, in order: `declared`, `statically_extracted`, `compiler_derived`,\n`typechecker_observed`, `runtime_observed`, `agent_inferred`.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).',
    )
    limitations: list[str]
    lock_artifact_id: str | None
    mode: Mode4
    observations: list[ProcessObservation]
    producer_runs: list[ProducerRun]
    profile: Profile = Field(
        ...,
        description="The three execution profiles (§10).\n\nThe values are, in order: `static`, `build`, `runtime`.",
    )
    result_artifact_id: str
    snippet_artifact_id: str
    snippet_origin: str
    source_context_id: str
    source_snapshot_id: str
    test_intent: str | None


class LibraryEnrichmentToolData1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    derived_context: Context | None
    derived_snapshot_id: str | None
    environment: Environment | None
    evidence_class: EvidenceClass = Field(
        ...,
        description='The six epistemic classes (blueprint §6.2).\n\nThese are categories, not a confidence scale. An API signature can be `compiler_derived`\nwhile "this replaces our orchestration layer" is `agent_inferred`, and the two never merge.\n\nThe values are, in order: `declared`, `statically_extracted`, `compiler_derived`,\n`typechecker_observed`, `runtime_observed`, `agent_inferred`.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).',
    )
    limitations: list[str]
    lock_artifact_id: str | None
    mode: Mode
    observations: list[ProcessObservation]
    producer_runs: list[ProducerRun]
    profile: Profile = Field(
        ...,
        description="The three execution profiles (§10).\n\nThe values are, in order: `static`, `build`, `runtime`.",
    )
    result_artifact_id: str
    snippet_artifact_id: str
    snippet_origin: str
    source_context_id: str
    source_snapshot_id: str
    test_intent: str | None
    tool: Literal["verify_usage"]


class LibraryEnrichmentToolData4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answered_from_cache: bool = Field(
        ...,
        description="Whether this answer was replayed from a recorded resolution rather than fetched.",
    )
    artifacts: list[Artifact] = Field(
        ..., description="Every artifact this resolution stored or reused."
    )
    context: Context = Field(..., description="The context identity every later call takes.")
    environment: Environment = Field(
        ..., description="The environment the context binds, with its resolution status."
    )
    gaps: list[Gap] = Field(
        ...,
        description="Expected evidence that is absent, each with a reason and a planned fallback.",
    )
    hosted_rustdoc_json: HostedJsonReport | None = Field(
        ..., description="Hosted rustdoc JSON availability."
    )
    observed_configuration: DocsRsMetadata | None = Field(
        ...,
        description="The maintainer's docs.rs build configuration, read from the crate manifest.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Provenance for each producer that ran."
    )
    python: Distribution | None = Field(
        ..., description="Distribution metadata and file inventory, only for Python."
    )
    release: Release = Field(
        ...,
        description="The release that was resolved. Its version is the one asked for, never an upgrade.",
    )
    snapshot: SnapshotSummary | None = Field(
        ...,
        description="The snapshot published from this resolution, when normalization succeeded.",
    )
    tool: Literal["resolve_library"]
    upstream: UpstreamCheck | None = Field(
        ...,
        description="What the registry said about newer releases, kept apart from the resolution.",
    )


class LibraryEnrichmentToolData9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    control_version: int = Field(..., ge=0)
    is_current: bool = Field(..., description="Whether this snapshot is the context's current one.")
    manifest: EvidenceManifest = Field(..., description="The immutable manifest as published.")
    previous_snapshot_id: str | None
    producer_runs: list[ProducerRun] = Field(
        ...,
        description="Operational attribution from the catalog generation pinned by this request.",
    )
    publication_changes: list[RelationChanges]
    tool: Literal["snapshot_manifest"]


class Alternative(BaseModel):
    source: FactSource | None
    value: AlternativeValue


class ApiObservationProjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    docs_included: bool = Field(
        ...,
        description="False means docs were omitted by projection; it does not assert absent documentation.",
    )
    environment_id: str
    observation_id: str = Field(
        ...,
        description="Identity of the complete admitted fact, not a hash of this query projection.",
    )
    origin: ApiOrigin
    payload: ApiPayload
    source: FactSource
    subject: SubjectRef


class Change(BaseModel):
    after: list[Alternative] | None
    after_page: Page
    before: list[Alternative] | None
    before_page: Page = Field(
        ..., description="Values and their source references share this bounded alternative order."
    )
    change_id: str
    interpretation: str
    kind: ChangeKind
    scope: Scope
    subject: str


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assessments: list[ScopeAssessment] = Field(
        ..., description="Requested evidence scopes assessed against qualified native facts."
    )
    details: RecoveryAction | None = Field(
        ...,
        description="When present, additional limitation text is retained in the exact coverage section.\nScope, assessments, indexed and missing remain the authoritative inline assessment.",
    )
    indexed: list[str] = Field(..., description="Evidence kinds that were successfully indexed.")
    limitations: list[str] = Field(..., description="Known reasons this result may not generalize.")
    missing: list[str] = Field(..., description="Evidence kinds that were expected but are absent.")
    scope: str = Field(..., description="What the result claims to cover, in prose.")


class DeliveryDescriptor5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: str
    limits: DeliveryLimits
    mode: Literal["artifact"]
    read: RecoveryAction
    sections: list[ResultSection]


class DeliveryDescriptor3(RootModel[DeliveryDescriptor | DeliveryDescriptor5]):
    root: DeliveryDescriptor | DeliveryDescriptor5 = Field(
        ...,
        description="Delivery changes representation, never the original research status or coverage.",
    )


class Diagnostic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actions: list[RecoveryAction]
    affected_ids: list[str]
    allowed: int | None = Field(..., ge=0)
    cause: DiagnosticCause
    correlation_id: str | None
    observed: int | None = Field(..., ge=0)
    rule: str | None
    stage: str


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Code = Field(..., description="The stable code a caller can branch on.")
    diagnostic: Diagnostic = Field(..., description="Structured origin and recovery evidence.")
    message: str = Field(..., description="Human-readable explanation. Not a stable interface.")
    next_action: str = Field(
        ...,
        description="What the caller should do instead. Blueprint §7.2 requires this, not just a code.",
    )
    retryable: bool = Field(
        ..., description="Whether retrying the identical request could succeed."
    )


class ExecutionPayload1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["semantic_query"]
    value: SemanticQuery


class ExecutionPayload(RootModel[ExecutionPayload1 | ExecutionPayload2 | ExecutionPayload3]):
    root: ExecutionPayload1 | ExecutionPayload2 | ExecutionPayload3


class ExecutionReadiness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actions: list[RecoveryAction]
    available: bool
    ecosystem: Ecosystem = Field(
        ...,
        description="Which package ecosystem a release belongs to.\n\nThe values are, in order: `rust`, `python`. No variant carries a doc comment -- see the\nmodule docs in [`crate::wire`].",
    )
    image_id: str | None
    prerequisites: list[ExecutionPrerequisite]
    profile: Profile = Field(
        ...,
        description="The three execution profiles (§10).\n\nThe values are, in order: `static`, `build`, `runtime`.",
    )


class FragmentProjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: RecoveryAction | None = Field(
        ..., description="A complete-text request for this selection when text was projected."
    )
    fragment: EvidenceFragment
    text_complete: bool


class JobResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    outcome: Outcome | None = None
    context_id: str | None
    coverage: Coverage
    delivery: DeliveryDescriptor3
    error: Error | None
    snapshot_id: str | None
    summary: str


class ManifestData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    control_version: int = Field(..., ge=0)
    is_current: bool = Field(..., description="Whether this snapshot is the context's current one.")
    manifest: EvidenceManifest = Field(..., description="The immutable manifest as published.")
    previous_snapshot_id: str | None
    producer_runs: list[ProducerRun] = Field(
        ...,
        description="Operational attribution from the catalog generation pinned by this request.",
    )
    publication_changes: list[RelationChanges]


class Sandbox(BaseModel):
    admitted_images: dict[str, str] = Field(
        ..., description="The image IDs a qualification receipt covers. Empty when there is none."
    )
    available_runtimes: list[str] = Field(
        ...,
        description="Container/isolation runtimes detected on this host.\n\nDetection only. A runtime being present is not the same as a profile being enabled, and\nthis never enables one.",
    )
    enabled_profiles: list[str] = Field(
        ...,
        description="Profiles configuration has enabled.\n\nRead from `LIBENR_CONFIG`; `enabled_profiles_source` names the file, or says these are\nbuilt-in defaults. A caller selects from this list and never grants itself permission.",
    )
    enabled_profiles_source: str = Field(
        ...,
        description="Where `enabled_profiles` came from, so a caller is never misled about policy.",
    )
    execution_qualified: bool = Field(
        ...,
        description="Whether an actual containment run has qualified the configured execution images.\n\nThree different facts live next to each other here on purpose: a profile can be\n*enabled*, a runtime can be *present*, and images can be *configured*, and none of the\nthree means the service can contain anything. Only `execution_qualified` says that, and\nit is set only by a receipt from `just execution-qualify`.",
    )
    execution_readiness: str = Field(
        ...,
        description="When qualification happened and against which images, or the missing prerequisite.",
    )
    execution_routes: list[ExecutionReadiness] = Field(
        ...,
        description="Implemented execution routes assessed by the same admission logic used by tools.\nEmpty when no running service is available to assess qualification and cleanup.",
    )


class StatusData(BaseModel):
    features: list[ComponentStatus] = Field(
        ..., description="Optional capabilities and whether each is supported."
    )
    health: Health = Field(..., description="Job queue and cache health.")
    producers: list[ComponentStatus] = Field(
        ..., description="Evidence producers and whether each is installed."
    )
    sandbox: Sandbox = Field(..., description="Which execution profiles are actually usable here.")
    schema_compatibility: SchemaCompatibility = Field(
        ..., description="Which wire schema versions this daemon can speak."
    )
    snapshot_compatibility: SchemaCompatibility = Field(
        ..., description="On-disk storage compatibility; independent of the MCP response envelope."
    )
    versions: Versions = Field(..., description="Component versions.")


class LibraryEnrichmentToolData2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_interests: int = Field(..., ge=0)
    interest_token: str | None
    job_id: str
    result: JobResult | None
    stage: str
    state: State = Field(
        ...,
        description="The persisted job states (blueprint §8.3).\n\nThe values are, in order: `queued`, `running`, `succeeded`, `partial`, `failed`,\n`cancel_requested`, `cancelled`. `cancel_requested` is distinct from `cancelled` because\ncancelling one caller's interest must not kill work another caller still needs.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).",
    )
    submitted_at: str
    tool: Literal["job_control"]
    updated_at: str


class LibraryEnrichmentToolData10(BaseModel):
    features: list[ComponentStatus] = Field(
        ..., description="Optional capabilities and whether each is supported."
    )
    health: Health = Field(..., description="Job queue and cache health.")
    producers: list[ComponentStatus] = Field(
        ..., description="Evidence producers and whether each is installed."
    )
    sandbox: Sandbox = Field(..., description="Which execution profiles are actually usable here.")
    schema_compatibility: SchemaCompatibility = Field(
        ..., description="Which wire schema versions this daemon can speak."
    )
    snapshot_compatibility: SchemaCompatibility = Field(
        ..., description="On-disk storage compatibility; independent of the MCP response envelope."
    )
    versions: Versions = Field(..., description="Component versions.")
    tool: Literal["service_status"]


class AspectOutcome(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aspect: InspectionAspect
    diagnostic: Diagnostic | None
    page: Page | None
    reason: str | None
    state: AspectState


class ComparisonSide(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: str
    coverage: Coverage
    environment: Environment
    release: Release
    snapshot_id: str


class DiscoveryFacet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    diagnostic: Diagnostic | None
    items: list[FragmentProjection]
    kind: DiscoveryKind
    page: Page | None
    reason: str | None
    state: AspectState


class ExecutionObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    containment_identity: str
    environment_id: str
    image_id: str
    observation_id: str
    payload: ExecutionPayload
    source: FactSource
    subject: SubjectRef


class InspectData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    aspect_outcomes: list[AspectOutcome] = Field(
        ..., description="Independent aspect states and continuations."
    )
    aspects: list[str] = Field(..., description="The aspects actually returned.")
    availability: Availability | None = Field(
        ..., description="What can and cannot be said about availability."
    )
    candidates: list[InspectionCandidate] = Field(
        ...,
        description="Distinct selectable definitions; public paths alone may collide across kinds.",
    )
    children: list[InspectionCandidate] = Field(
        ...,
        description="Lexical direct children, independently paged; this does not establish typed membership.",
    )
    docs_truncated: bool = Field(..., description="Whether `docs` was cut to fit.")
    execution_observations: list[ExecutionObservation] = Field(
        ...,
        description="Retained execution facts selected natively by symbol/document and exact scope.",
    )
    fragments: list[FragmentProjection] = Field(
        ..., description="Fragments about the symbol, bounded."
    )
    members: list[InspectionCandidate] = Field(
        ...,
        description="Bindings reached by qualified member_of relationships, independently paged.",
    )
    observations: list[ApiObservationProjection] = Field(
        ...,
        description="Qualified projections; complete immutable observations remain in the snapshot.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Actual attempt attribution for an execution job result."
    )
    relationships: list[RelationshipObservation] = Field(
        ..., description="Typed edges touching the symbol."
    )
    source: SourceExcerpt | None = Field(..., description="Source excerpt at `source` depth.")
    symbol: Symbol | None = Field(
        ..., description="The symbol, when one was selected. Its `docs` are bounded here."
    )


class JobData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_interests: int = Field(..., ge=0)
    interest_token: str | None
    job_id: str
    result: JobResult | None
    stage: str
    state: State3 = Field(
        ...,
        description="The persisted job states (blueprint §8.3).\n\nThe values are, in order: `queued`, `running`, `succeeded`, `partial`, `failed`,\n`cancel_requested`, `cancelled`. `cancel_requested` is distinct from `cancelled` because\ncancelling one caller's interest must not kill work another caller still needs.\n\nNo variant carries a doc comment -- see the module docs in [`super`](crate::wire).",
    )
    submitted_at: str
    updated_at: str


class OverviewData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(..., description="The subtree the overview was narrowed to, when any.")
    crate_name: str = Field(..., description="The crate's root module name.")
    crate_version: str | None = Field(
        ..., description="The crate version the documentation declares."
    )
    definitions_by_kind: dict[str, DefinitionsByKind] = Field(
        ..., description="Distinct definitions by kind across the area."
    )
    discovery: list[DiscoveryFacet] = Field(
        ...,
        description="Library-level retained fragments, preserving independently sourced alternatives.",
    )
    namespaces: list[NamespaceFacet] = Field(..., description="Namespaces, root first.")
    observed_configuration: ObservedConfiguration | None = Field(
        ..., description="The documentation build's configuration."
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    snapshot: SnapshotSummary = Field(..., description="The snapshot read.")
    truncated_namespaces: int = Field(..., description="Namespaces beyond the returned set.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )


class LibraryEnrichmentToolData3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after: ComparisonSide
    api_complete: bool
    before: ComparisonSide
    changes: list[Change]
    comparable: bool
    configuration_differences: list[ConfigurationDifference]
    confounders: list[str]
    offset: int = Field(..., ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    same_release: bool
    scopes: list[Scope]
    tool: Literal["compare_releases"]
    total_changes: int = Field(..., ge=0)


class LibraryEnrichmentToolData5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: str | None = Field(..., description="The subtree the overview was narrowed to, when any.")
    crate_name: str = Field(..., description="The crate's root module name.")
    crate_version: str | None = Field(
        ..., description="The crate version the documentation declares."
    )
    definitions_by_kind: dict[str, DefinitionsByKind] = Field(
        ..., description="Distinct definitions by kind across the area."
    )
    discovery: list[DiscoveryFacet] = Field(
        ...,
        description="Library-level retained fragments, preserving independently sourced alternatives.",
    )
    namespaces: list[NamespaceFacet] = Field(..., description="Namespaces, root first.")
    observed_configuration: ObservedConfiguration | None = Field(
        ..., description="The documentation build's configuration."
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    snapshot: SnapshotSummary = Field(..., description="The snapshot read.")
    tool: Literal["library_overview"]
    truncated_namespaces: int = Field(..., description="Namespaces beyond the returned set.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )


class LibraryEnrichmentToolData7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    aspect_outcomes: list[AspectOutcome] = Field(
        ..., description="Independent aspect states and continuations."
    )
    aspects: list[str] = Field(..., description="The aspects actually returned.")
    availability: Availability | None = Field(
        ..., description="What can and cannot be said about availability."
    )
    candidates: list[InspectionCandidate] = Field(
        ...,
        description="Distinct selectable definitions; public paths alone may collide across kinds.",
    )
    children: list[InspectionCandidate] = Field(
        ...,
        description="Lexical direct children, independently paged; this does not establish typed membership.",
    )
    docs_truncated: bool = Field(..., description="Whether `docs` was cut to fit.")
    execution_observations: list[ExecutionObservation] = Field(
        ...,
        description="Retained execution facts selected natively by symbol/document and exact scope.",
    )
    fragments: list[FragmentProjection] = Field(
        ..., description="Fragments about the symbol, bounded."
    )
    members: list[InspectionCandidate] = Field(
        ...,
        description="Bindings reached by qualified member_of relationships, independently paged.",
    )
    observations: list[ApiObservationProjection] = Field(
        ...,
        description="Qualified projections; complete immutable observations remain in the snapshot.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Actual attempt attribution for an execution job result."
    )
    relationships: list[RelationshipObservation] = Field(
        ..., description="Typed edges touching the symbol."
    )
    source: SourceExcerpt | None = Field(..., description="Source excerpt at `source` depth.")
    symbol: Symbol | None = Field(
        ..., description="The symbol, when one was selected. Its `docs` are bounded here."
    )
    tool: Literal["inspect_symbol"]


class LibraryEnrichmentToolData(
    RootModel[
        LibraryEnrichmentToolData1
        | LibraryEnrichmentToolData2
        | LibraryEnrichmentToolData3
        | LibraryEnrichmentToolData4
        | LibraryEnrichmentToolData5
        | LibraryEnrichmentToolData6
        | LibraryEnrichmentToolData7
        | LibraryEnrichmentToolData8
        | LibraryEnrichmentToolData9
        | LibraryEnrichmentToolData10
    ]
):
    root: (
        LibraryEnrichmentToolData1
        | LibraryEnrichmentToolData2
        | LibraryEnrichmentToolData3
        | LibraryEnrichmentToolData4
        | LibraryEnrichmentToolData5
        | LibraryEnrichmentToolData6
        | LibraryEnrichmentToolData7
        | LibraryEnrichmentToolData8
        | LibraryEnrichmentToolData9
        | LibraryEnrichmentToolData10
    ) = Field(
        ...,
        description="Every tool payload, for schema emission. Never sent on the wire as a union.",
        title="LibraryEnrichmentToolData",
    )


class CompareData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after: ComparisonSide
    api_complete: bool
    before: ComparisonSide
    changes: list[Change]
    comparable: bool
    configuration_differences: list[ConfigurationDifference]
    confounders: list[str]
    offset: int = Field(..., ge=0)
    page: Page = Field(
        ..., description="Bounded page over this payload, not over the whole research envelope."
    )
    same_release: bool
    scopes: list[Scope]
    total_changes: int = Field(..., ge=0)
