# generated by datamodel-codegen:
#   filename:  tool-data.schema.json
#   timestamp: 2026-09-13T22:38:10+00:00

from pydantic import BaseModel, Field, RootModel
from enum import Enum, StrEnum
from typing import Any, Literal


class DefinitionsByKind(RootModel[int]):
    root: int = Field(..., ge=0)


class Encoding(StrEnum):
    utf8 = "utf8"
    base64 = "base64"


class Kind(StrEnum):
    registry_index_entry = "registry_index_entry"
    registry_version_metadata = "registry_version_metadata"
    crate_tarball = "crate_tarball"
    rustdoc_json = "rustdoc_json"
    cargo_manifest = "cargo_manifest"
    readme = "readme"
    changelog = "changelog"
    source_file = "source_file"
    other = "other"


class Artifact(BaseModel):
    artifact_id: str = Field(
        ...,
        description="`art_<32 hex>`, derived from the digest; the handle callers pass to `read_artifact`.",
    )
    compression: str | None = Field(
        ..., description="Transport compression that was removed before storage, e.g. `zstd`."
    )
    etag: str | None = Field(..., description="HTTP validator, when the server supplied one.")
    final_url: str | None = Field(
        ..., description="Where it was actually served from after redirects, when different."
    )
    kind: Kind = Field(..., description="What the artifact is.")
    last_modified: str | None = Field(
        ..., description="HTTP validator, when the server supplied one."
    )
    media_type: str = Field(
        ..., description="Media type of the stored bytes (after any transport decompression)."
    )
    retrieved_at: str = Field(
        ...,
        description="When it was retrieved, RFC 3339. Provenance only; never part of any identity.",
    )
    sha256: str = Field(..., description="Full SHA-256 of the stored bytes, lower-case hex.")
    size_bytes: int = Field(..., description="Size of the stored bytes.", ge=0)
    source_uri: str = Field(..., description="Where it was requested from.")


class ArtifactSliceData(BaseModel):
    artifact: Artifact = Field(..., description="The artifact record.")
    content: str = Field(..., description="The slice.")
    content_digest: str = Field(..., description="SHA-256 of the slice bytes.")
    encoding: Encoding = Field(..., description="How `content` is encoded.")
    end: int = Field(..., description="One past the last byte offset of the slice.", ge=0)
    remaining: int = Field(..., description="Bytes after `end`.", ge=0)
    section: str | None = Field(..., description="The section that was selected, when one was.")
    start: int = Field(..., description="First byte offset of the slice.", ge=0)
    total: int = Field(..., description="Total artifact size.", ge=0)


class Status(StrEnum):
    documented_available = "documented_available"
    project_availability_unverified = "project_availability_unverified"


class Mode(StrEnum):
    project = "project"
    upstream = "upstream"
    compare = "compare"
    revision = "revision"


class Context(BaseModel):
    context_id: str = Field(
        ..., description="Derived from release, environment and mode.", pattern="^ctx_[0-9a-f]{16}$"
    )
    environment_id: str = Field(
        ..., description="The environment it is studied in.", pattern="^env_[0-9a-f]{16}$"
    )
    mode: Mode = Field(..., description="The research mode.")
    parent_context_id: str | None = Field(
        ...,
        description="The context this one was derived from, if any.",
        pattern="^ctx_[0-9a-f]{16}$",
    )
    release_id: str = Field(
        ..., description="The release under study.", pattern="^rel_[0-9a-f]{16}$"
    )


class Deprecated(BaseModel):
    note: str | None = Field(..., description="The note, if given.")
    since: str | None = Field(..., description="The `since` value, if given.")


class DocsRsMetadata(BaseModel):
    additional_targets: list[str] = Field(..., description="Targets added to the default set.")
    all_features: bool = Field(..., description="Whether all features were enabled.")
    cargo_args: list[str] = Field(
        ..., description="Extra `cargo` arguments; these can change what compiles at all."
    )
    declared: bool = Field(..., description="Whether the manifest declared the table.")
    default_target: str = Field(..., description="The default target.")
    features: list[str] = Field(..., description="Features enabled for the docs build.")
    no_default_features: bool = Field(..., description="Whether default features were disabled.")
    rustc_args: list[str] = Field(
        ..., description="Extra `rustc` arguments; these can change what compiles at all."
    )
    rustdoc_args: list[str] = Field(..., description="Extra `rustdoc` arguments.")
    targets: list[str] | None = Field(
        ...,
        description="Explicit target list, when set; `None` means docs.rs' tier-one default set.",
    )


class Resolution(StrEnum):
    unspecified = "unspecified"
    declared = "declared"
    resolved = "resolved"
    verified = "verified"


class Environment(BaseModel):
    default_features: bool | None = Field(
        ..., description="Whether default features are enabled. `None` when unspecified."
    )
    environment_id: str = Field(
        ..., description="Derived from every other field.", pattern="^env_[0-9a-f]{16}$"
    )
    features: list[str] = Field(
        ..., description="Enabled features or extras, sorted and deduplicated."
    )
    lock_digest: str | None = Field(
        ..., description="Digest of the dependency lock, when one was supplied."
    )
    resolution: Resolution = Field(..., description="How much of this environment is known.")
    target: str | None = Field(..., description="Target triple or platform tag, when known.")
    toolchain: str | None = Field(..., description="Compiler or interpreter identity, when known.")


class EvidenceClass(StrEnum):
    declared = "declared"
    statically_extracted = "statically_extracted"
    compiler_derived = "compiler_derived"
    typechecker_observed = "typechecker_observed"
    runtime_observed = "runtime_observed"
    agent_inferred = "agent_inferred"


class Kind1(StrEnum):
    api_signature = "api_signature"
    doc_text = "doc_text"
    feature_definition = "feature_definition"
    readme_section = "readme_section"
    changelog_section = "changelog_section"
    example = "example"
    source_excerpt = "source_excerpt"


class EvidenceFragment(BaseModel):
    artifact_id: str = Field(..., description="The artifact it was read from.")
    evidence_class: EvidenceClass = Field(..., description="Which epistemic class it belongs to.")
    fragment_id: str = Field(..., description="Content-derived identity.")
    kind: Kind1 = Field(..., description="What kind of text this is.")
    locator: dict[str, Any] = Field(
        ..., description="Position within the artifact, as a JSON object."
    )
    producer: str = Field(..., description="Which producer emitted it.")
    producer_version: str = Field(..., description="The producer's exact version.")
    subject: str = Field(
        ..., description="What it is about: a symbol path, a feature name, a heading."
    )
    text: str = Field(..., description="The text.")


class Kind2(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"


class Reason(StrEnum):
    hosted_json_missing = "hosted_json_missing"
    hosted_json_unsupported = "hosted_json_unsupported"
    upstream_unavailable = "upstream_unavailable"
    policy_denied = "policy_denied"
    extraction_failed = "extraction_failed"
    not_attempted = "not_attempted"


class State(StrEnum):
    available = "available"
    missing = "missing"
    unsupported = "unsupported"
    not_attempted = "not_attempted"


class SupportedFormat(RootModel[int]):
    root: int = Field(..., ge=0)


class HostedJsonReport(BaseModel):
    declared_crate_version: str | None = Field(
        ..., description="`crate_version` as the JSON itself declares it, when available."
    )
    format_version: int | None = Field(
        ..., description="The format version the payload declared, when one was read.", ge=0
    )
    state: State = Field(..., description="What was found.")
    supported_formats: list[SupportedFormat] = Field(
        ..., description="The format versions this build can interpret."
    )
    target: str = Field(..., description="The target the JSON was requested for.")
    url: str = Field(..., description="The URL that was asked.")


class CountsByKind(RootModel[int]):
    root: int = Field(..., ge=0)


class ObservedConfiguration(BaseModel):
    all_features: bool = Field(..., description="Whether all features were enabled.")
    features: list[str] = Field(
        ..., description="Features the docs build enabled, as the manifest declared them."
    )
    format_version: int = Field(..., description="The rustdoc JSON format version.", ge=0)
    no_default_features: bool = Field(..., description="Whether default features were disabled.")
    source: str = Field(..., description="Where the configuration was read from.")
    target: str = Field(..., description="The target the JSON itself declares.")


class Kind3(StrEnum):
    module = "module"
    struct = "struct"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    import_ = "import"


class OverviewChild(BaseModel):
    deprecated: bool = Field(..., description="Whether deprecated.")
    doc_summary: str | None = Field(..., description="Summary, when documented.")
    is_reexport: bool = Field(
        ..., description="Whether this path re-exports a definition elsewhere."
    )
    kind: Kind3 = Field(..., description="Kind.")
    path: str = Field(..., description="Public path.")


class PlannedFallback(BaseModel):
    enabled: bool = Field(..., description="Whether configuration currently enables that profile.")
    next_action: str = Field(..., description="What a caller or operator would do to make it run.")
    producer: str = Field(..., description="Producer name.")
    profile: str = Field(..., description="The execution profile it needs.")


class Outcome(StrEnum):
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    skipped = "skipped"


class Profile(StrEnum):
    static = "static"
    build = "build"
    runtime = "runtime"


class Relation(StrEnum):
    reexports = "reexports"
    implements = "implements"
    member_of = "member_of"
    documents = "documents"
    returns = "returns"
    accepts = "accepts"


class Relationship(BaseModel):
    detail: str | None = Field(
        ..., description="A qualifier such as `blanket`, `auto` or `trait_impl`."
    )
    producer: str = Field(..., description="Which producer emitted it.")
    relation: Relation = Field(..., description="The relation.")
    relationship_id: str = Field(..., description="Content-derived identity.")
    source_id: str = Field(..., description="The source symbol.")
    source_path: str = Field(..., description="The source path, for display without a join.")
    target_id: str | None = Field(
        ..., description="The target symbol or definition, when it is in this snapshot."
    )
    target_path: str = Field(
        ..., description="The target path as written, even when the target is external."
    )


class Ecosystem(StrEnum):
    rust = "rust"
    python = "python"


class ReleaseLinks(BaseModel):
    documentation: str | None = Field(..., description="Documentation site.")
    homepage: str | None = Field(..., description="Project homepage.")
    repository: str | None = Field(..., description="Source repository.")


class RequestedConfiguration(BaseModel):
    default_features: bool | None = Field(
        ..., description="Whether default features are enabled, when declared."
    )
    features: list[str] | None = Field(
        ..., description="Features the project enables, when declared."
    )
    target: str | None = Field(..., description="The project's target, when declared.")


class ScoreFactor(BaseModel):
    name: str = Field(..., description="Factor name.")
    points: int = Field(..., description="Points contributed.", ge=0)


class FragmentKind(Enum):
    api_signature = "api_signature"
    doc_text = "doc_text"
    feature_definition = "feature_definition"
    readme_section = "readme_section"
    changelog_section = "changelog_section"
    example = "example"
    source_excerpt = "source_excerpt"
    NoneType_None = None


class Hit(StrEnum):
    symbol = "symbol"
    fragment = "fragment"


class SymbolKind(Enum):
    module = "module"
    struct = "struct"
    union = "union"
    enum = "enum"
    variant = "variant"
    struct_field = "struct_field"
    trait = "trait"
    trait_alias = "trait_alias"
    type_alias = "type_alias"
    function = "function"
    method = "method"
    constant = "constant"
    static = "static"
    macro = "macro"
    proc_macro = "proc_macro"
    assoc_type = "assoc_type"
    assoc_const = "assoc_const"
    primitive = "primitive"
    extern_crate = "extern_crate"
    import_ = "import"
    NoneType_None = None


class SearchHit(BaseModel):
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    deprecated: bool = Field(..., description="Whether the symbol is deprecated.")
    evidence_id: str = Field(..., description="The evidence entry this hit is cited by.")
    excerpt: str = Field(..., description="Bounded excerpt.")
    factors: list[ScoreFactor] = Field(..., description="The factors behind the score.")
    fragment_kind: FragmentKind | None = Field(..., description="Fragment kind, for fragment hits.")
    hit: Hit = Field(..., description="Symbol or fragment.")
    path: str | None = Field(..., description="Symbol path, for symbol hits.")
    score: int = Field(..., description="Total score.", ge=0)
    signature: str | None = Field(..., description="Rendered signature, for symbol hits.")
    subject: str | None = Field(..., description="Fragment subject, for fragment hits.")
    symbol_kind: SymbolKind | None = Field(..., description="Symbol kind, for symbol hits.")


class SnapshotCounts(BaseModel):
    definitions: int = Field(..., description="Distinct definitions.", ge=0)
    fragments: int = Field(..., description="Fragments.", ge=0)
    producer_items: int = Field(
        ...,
        description="Items the producer saw in total, including those not surfaced as symbols.",
        ge=0,
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    relationships: int = Field(..., description="Typed edges.", ge=0)
    symbols: int = Field(..., description="Public paths.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )


class IndexedEnum(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"


class MissingEnum(StrEnum):
    registry_metadata = "registry_metadata"
    crate_source = "crate_source"
    documentation_build_config = "documentation_build_config"
    hosted_rustdoc_json = "hosted_rustdoc_json"
    public_api = "public_api"
    documentation = "documentation"
    examples = "examples"
    release_notes = "release_notes"
    source_excerpts = "source_excerpts"


class SnapshotSummary(BaseModel):
    counts: SnapshotCounts = Field(..., description="Counts.")
    normalizer_version: str = Field(..., description="Normalizer version that produced it.")
    published_at: str = Field(..., description="Publication time.")
    snapshot_id: str = Field(..., description="The snapshot identity.")


class SourceExcerpt(BaseModel):
    end_line: int = Field(..., description="Last line included, 1-based.", ge=0)
    path: str = Field(..., description="The file, relative to the crate root.")
    start_line: int = Field(..., description="First line included, 1-based.", ge=0)
    text: str = Field(..., description="The text.")
    truncated: bool = Field(..., description="Whether the file had more lines after `end_line`.")


class Symbol(BaseModel):
    cfg_hints: list[str] = Field(
        ...,
        description="`cfg`-shaped attribute strings the producer preserved, as declared hints only. Never\na feature predicate: items compiled out are absent, not annotated (§4.3).",
    )
    defined_in_crate: str = Field(..., description="The crate the definition belongs to.")
    definition_id: str = Field(..., description="Identity of the definition this path names.")
    definition_path: str = Field(..., description="The path the item is defined at.")
    deprecated: Deprecated | None = Field(..., description="Deprecation, when marked.")
    doc_summary: str | None = Field(
        ..., description="First paragraph of the documentation, bounded."
    )
    docs: str | None = Field(..., description="Full documentation text.")
    is_reexport: bool = Field(
        ..., description="Whether this path is a re-export of a definition elsewhere."
    )
    kind: Kind3 = Field(..., description="What kind of item this is.")
    name: str = Field(..., description="The last path segment.")
    parent_path: str | None = Field(..., description="The containing path, when any.")
    path: str = Field(..., description="Canonical public path, e.g. `enr_fixture::inner::Widget`.")
    producer_local_id: int = Field(
        ...,
        description="The producer's own item identifier -- local, never a cross-release identity.",
        ge=0,
    )
    signature: str | None = Field(
        ..., description="Rendered signature, when the producer rendered one."
    )
    span_file: str | None = Field(..., description="Source file as the producer recorded it.")
    span_line: int | None = Field(
        ..., description="1-based source line as the producer recorded it.", ge=0
    )
    symbol_id: str = Field(
        ...,
        description="Identity of this public path: hash of crate, path, kind and (for trait-impl members)\nthe trait.",
    )


class TableRef(BaseModel):
    file: str = Field(..., description="File name within the snapshot directory.")
    rows: int = Field(..., description="Row count at publication.", ge=0)


class UpstreamCheck(BaseModel):
    newest_any: str | None = Field(..., description="Newest non-yanked version of any kind.")
    newest_stable: str | None = Field(..., description="Newest non-yanked, non-prerelease version.")
    published_versions: int = Field(
        ..., description="Number of published versions the index listed.", ge=0
    )
    resolved_is_newest_stable: bool = Field(
        ..., description="Whether the resolved version is the newest stable one."
    )


class LibraryEnrichmentToolData3(BaseModel):
    hits: list[SearchHit] = Field(..., description="The hits on this page.")
    kinds: list[str] = Field(..., description="The evidence families searched.")
    offset: int = Field(..., description="Page offset.", ge=0)
    query: str = Field(..., description="The query as asked.")
    scoring: list[ScoreFactor] = Field(..., description="The scoring legend, in rank order.")
    searched: list[str] = Field(..., description="Which sources were searched.")
    tokens: list[str] = Field(..., description="The tokens it was split into.")
    tool: Literal["search_evidence"]


class LibraryEnrichmentToolData5(BaseModel):
    artifact: Artifact = Field(..., description="The artifact record.")
    content: str = Field(..., description="The slice.")
    content_digest: str = Field(..., description="SHA-256 of the slice bytes.")
    encoding: Encoding = Field(..., description="How `content` is encoded.")
    end: int = Field(..., description="One past the last byte offset of the slice.", ge=0)
    remaining: int = Field(..., description="Bytes after `end`.", ge=0)
    section: str | None = Field(..., description="The section that was selected, when one was.")
    start: int = Field(..., description="First byte offset of the slice.", ge=0)
    total: int = Field(..., description="Total artifact size.", ge=0)
    tool: Literal["read_artifact"]


class Availability(BaseModel):
    notes: list[str] = Field(..., description="Why the status is what it is, in prose.")
    observed_configuration: ObservedConfiguration = Field(
        ..., description="The documented build's configuration."
    )
    requested_configuration: RequestedConfiguration = Field(
        ..., description="The caller's declared configuration."
    )
    status: Status = Field(..., description="The strongest honest claim.")


class Gap(BaseModel):
    detail: str = Field(
        ..., description="Human-readable detail, e.g. the format version that was refused."
    )
    kind: Kind2 = Field(..., description="What is missing.")
    planned_fallback: PlannedFallback | None = Field(
        ..., description="The producer and profile that would supply it, when one exists."
    )
    reason: Reason = Field(..., description="Why.")


class InspectData(BaseModel):
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    aspects: list[str] = Field(..., description="The aspects actually returned.")
    availability: Availability | None = Field(
        ..., description="What can and cannot be said about availability."
    )
    candidates: list[str] = Field(
        ..., description="Candidate paths when the reference was ambiguous or unqualified."
    )
    docs_truncated: bool = Field(..., description="Whether `docs` was cut to fit.")
    fragments: list[EvidenceFragment] = Field(
        ..., description="Fragments about the symbol, bounded."
    )
    relationships: list[Relationship] = Field(..., description="Typed edges touching the symbol.")
    source: SourceExcerpt | None = Field(..., description="Source excerpt at `source` depth.")
    symbol: Symbol | None = Field(
        ..., description="The symbol, when one was selected. Its `docs` are bounded here."
    )


class NamespaceFacet(BaseModel):
    children: list[OverviewChild] = Field(
        ..., description="A bounded sample of direct children, definitions counted once."
    )
    counts_by_kind: dict[str, CountsByKind] = Field(
        ..., description="Distinct definitions directly under this module, by kind."
    )
    doc_summary: str | None = Field(..., description="First paragraph of the module docs.")
    path: str = Field(..., description="The module path.")
    truncated_children: int = Field(..., description="Children beyond the sample.", ge=0)


class OverviewData(BaseModel):
    area: str | None = Field(..., description="The subtree the overview was narrowed to, when any.")
    crate_name: str = Field(..., description="The crate's root module name.")
    crate_version: str | None = Field(
        ..., description="The crate version the documentation declares."
    )
    definitions_by_kind: dict[str, DefinitionsByKind] = Field(
        ..., description="Distinct definitions by kind across the area."
    )
    documentation_headings: list[str] = Field(..., description="README headings, in order.")
    examples: list[str] = Field(..., description="Example names.")
    features: dict[str, str] = Field(
        ..., description="Feature definitions: name and what it enables."
    )
    namespaces: list[NamespaceFacet] = Field(..., description="Namespaces, root first.")
    observed_configuration: ObservedConfiguration = Field(
        ..., description="The documentation build's configuration."
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    release_note_headings: list[str] = Field(..., description="Changelog headings, in order.")
    snapshot: SnapshotSummary = Field(..., description="The snapshot read.")
    truncated_namespaces: int = Field(..., description="Namespaces beyond the returned set.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )


class ProducerRun(BaseModel):
    config_digest: str = Field(
        ..., description="Digest of the normalized options the run was configured with."
    )
    finished_at: str = Field(..., description="RFC 3339 finish time. Provenance only.")
    gaps: list[Gap] = Field(
        ..., description="Evidence the run was expected to yield and did not, each with a reason."
    )
    inputs: dict[str, str] = Field(..., description="Input artifact digests by role.")
    log: str | None = Field(..., description="Bounded log text, when any was kept.")
    outcome: Outcome = Field(..., description="How it ended.")
    producer: str = Field(..., description="Producer name.")
    producer_version: str = Field(..., description="Exact producer version.")
    profile: Profile = Field(..., description="The execution profile the run was performed under.")
    started_at: str = Field(..., description="RFC 3339 start time. Provenance only.")


class Release(BaseModel):
    artifact_digest: str | None = Field(
        ...,
        description="The registry checksum of the selected artifact, when the registry publishes one.",
    )
    ecosystem: Ecosystem = Field(..., description="Which ecosystem.")
    lib_name: str | None = Field(
        ..., description="The library target name declared in the manifest, when known."
    )
    license: str | None = Field(..., description="SPDX licence expression as published.")
    links: ReleaseLinks = Field(..., description="Registry-published links.")
    package: str = Field(..., description="The normalized package name as the registry knows it.")
    published_at: str | None = Field(
        ..., description="Publication time as the registry records it."
    )
    registry: str = Field(
        ..., description="The registry the package was resolved against, e.g. `crates.io`."
    )
    release_id: str = Field(
        ...,
        description="Derived from `key`; never set independently.",
        pattern="^rel_[0-9a-f]{16}$",
    )
    root_module: str | None = Field(
        ..., description="The root module name as it appears in `use` paths, when known."
    )
    rust_version: str | None = Field(
        ..., description="Minimum supported Rust version as published."
    )
    version: str = Field(
        ..., description="The exact version, or an immutable revision for `revision` mode."
    )
    yanked: bool = Field(..., description="Whether the registry has yanked this version.")


class ResolveData(BaseModel):
    answered_from_cache: bool = Field(
        ...,
        description="Whether this answer was replayed from a recorded resolution rather than fetched.",
    )
    artifacts: list[Artifact] = Field(
        ..., description="Every artifact this resolution stored or reused."
    )
    context: Context = Field(..., description="The context identity every later call takes.")
    environment: Environment = Field(
        ..., description="The environment the context binds, with its resolution status."
    )
    gaps: list[Gap] = Field(
        ...,
        description="Expected evidence that is absent, each with a reason and a planned fallback.",
    )
    hosted_rustdoc_json: HostedJsonReport = Field(
        ..., description="Hosted rustdoc JSON availability."
    )
    observed_configuration: DocsRsMetadata | None = Field(
        ...,
        description="The maintainer's docs.rs build configuration, read from the crate manifest.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Provenance for each producer that ran."
    )
    release: Release = Field(
        ...,
        description="The release that was resolved. Its version is the one asked for, never an upgrade.",
    )
    snapshot: SnapshotSummary | None = Field(
        ...,
        description="The snapshot published from this resolution, when normalization succeeded.",
    )
    upstream: UpstreamCheck | None = Field(
        ...,
        description="What the registry said about newer releases, kept apart from the resolution.",
    )


class SearchData(BaseModel):
    hits: list[SearchHit] = Field(..., description="The hits on this page.")
    kinds: list[str] = Field(..., description="The evidence families searched.")
    offset: int = Field(..., description="Page offset.", ge=0)
    query: str = Field(..., description="The query as asked.")
    scoring: list[ScoreFactor] = Field(..., description="The scoring legend, in rank order.")
    searched: list[str] = Field(..., description="Which sources were searched.")
    tokens: list[str] = Field(..., description="The tokens it was split into.")


class SnapshotManifest(BaseModel):
    context_id: str = Field(
        ..., description="The context this snapshot serves.", pattern="^ctx_[0-9a-f]{16}$"
    )
    counts: SnapshotCounts = Field(..., description="Counts.")
    crate_name: str = Field(..., description="The crate name as rustdoc knows it.")
    crate_version: str | None = Field(..., description="The crate version the JSON declared.")
    environment_id: str = Field(..., description="The environment.", pattern="^env_[0-9a-f]{16}$")
    indexed: list[IndexedEnum] = Field(..., description="Evidence kinds this snapshot contains.")
    inputs: dict[str, str] = Field(..., description="Input artifact digests by role.")
    missing: list[MissingEnum] = Field(
        ..., description="Evidence kinds that were expected and are absent."
    )
    normalizer_version: str = Field(..., description="Normalizer version at publication.")
    observed_configuration: ObservedConfiguration = Field(
        ..., description="The documentation build's configuration."
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Every producer run that fed this snapshot."
    )
    producers: dict[str, str] = Field(..., description="Producer identities by name.")
    published_at: str = Field(..., description="Publication time, RFC 3339. Provenance only.")
    release_id: str = Field(..., description="The release.", pattern="^rel_[0-9a-f]{16}$")
    schema_version: str = Field(..., description="Wire schema version at publication.")
    snapshot_id: str = Field(
        ..., description="The snapshot's identity.", pattern="^snap_[0-9a-f]{16}$"
    )
    tables: dict[str, TableRef] = Field(..., description="Tables and their row counts.")


class LibraryEnrichmentToolData1(BaseModel):
    answered_from_cache: bool = Field(
        ...,
        description="Whether this answer was replayed from a recorded resolution rather than fetched.",
    )
    artifacts: list[Artifact] = Field(
        ..., description="Every artifact this resolution stored or reused."
    )
    context: Context = Field(..., description="The context identity every later call takes.")
    environment: Environment = Field(
        ..., description="The environment the context binds, with its resolution status."
    )
    gaps: list[Gap] = Field(
        ...,
        description="Expected evidence that is absent, each with a reason and a planned fallback.",
    )
    hosted_rustdoc_json: HostedJsonReport = Field(
        ..., description="Hosted rustdoc JSON availability."
    )
    observed_configuration: DocsRsMetadata | None = Field(
        ...,
        description="The maintainer's docs.rs build configuration, read from the crate manifest.",
    )
    producer_runs: list[ProducerRun] = Field(
        ..., description="Provenance for each producer that ran."
    )
    release: Release = Field(
        ...,
        description="The release that was resolved. Its version is the one asked for, never an upgrade.",
    )
    snapshot: SnapshotSummary | None = Field(
        ...,
        description="The snapshot published from this resolution, when normalization succeeded.",
    )
    upstream: UpstreamCheck | None = Field(
        ...,
        description="What the registry said about newer releases, kept apart from the resolution.",
    )
    tool: Literal["resolve_library"]


class LibraryEnrichmentToolData2(BaseModel):
    area: str | None = Field(..., description="The subtree the overview was narrowed to, when any.")
    crate_name: str = Field(..., description="The crate's root module name.")
    crate_version: str | None = Field(
        ..., description="The crate version the documentation declares."
    )
    definitions_by_kind: dict[str, DefinitionsByKind] = Field(
        ..., description="Distinct definitions by kind across the area."
    )
    documentation_headings: list[str] = Field(..., description="README headings, in order.")
    examples: list[str] = Field(..., description="Example names.")
    features: dict[str, str] = Field(
        ..., description="Feature definitions: name and what it enables."
    )
    namespaces: list[NamespaceFacet] = Field(..., description="Namespaces, root first.")
    observed_configuration: ObservedConfiguration = Field(
        ..., description="The documentation build's configuration."
    )
    reexports: int = Field(
        ..., description="Paths that re-export a definition reachable elsewhere.", ge=0
    )
    release_note_headings: list[str] = Field(..., description="Changelog headings, in order.")
    snapshot: SnapshotSummary = Field(..., description="The snapshot read.")
    truncated_namespaces: int = Field(..., description="Namespaces beyond the returned set.", ge=0)
    unresolved_reexports: int = Field(
        ..., description="Re-exports whose target is outside this crate.", ge=0
    )
    tool: Literal["library_overview"]


class LibraryEnrichmentToolData4(BaseModel):
    also_at: list[str] = Field(..., description="Other public paths to the same definition.")
    aspects: list[str] = Field(..., description="The aspects actually returned.")
    availability: Availability | None = Field(
        ..., description="What can and cannot be said about availability."
    )
    candidates: list[str] = Field(
        ..., description="Candidate paths when the reference was ambiguous or unqualified."
    )
    docs_truncated: bool = Field(..., description="Whether `docs` was cut to fit.")
    fragments: list[EvidenceFragment] = Field(
        ..., description="Fragments about the symbol, bounded."
    )
    relationships: list[Relationship] = Field(..., description="Typed edges touching the symbol.")
    source: SourceExcerpt | None = Field(..., description="Source excerpt at `source` depth.")
    symbol: Symbol | None = Field(
        ..., description="The symbol, when one was selected. Its `docs` are bounded here."
    )
    tool: Literal["inspect_symbol"]


class LibraryEnrichmentToolData6(BaseModel):
    is_current: bool = Field(..., description="Whether this snapshot is the context's current one.")
    manifest: SnapshotManifest = Field(..., description="The immutable manifest as published.")
    tool: Literal["snapshot_manifest"]


class LibraryEnrichmentToolData(
    RootModel[
        LibraryEnrichmentToolData1
        | LibraryEnrichmentToolData2
        | LibraryEnrichmentToolData3
        | LibraryEnrichmentToolData4
        | LibraryEnrichmentToolData5
        | LibraryEnrichmentToolData6
    ]
):
    root: (
        LibraryEnrichmentToolData1
        | LibraryEnrichmentToolData2
        | LibraryEnrichmentToolData3
        | LibraryEnrichmentToolData4
        | LibraryEnrichmentToolData5
        | LibraryEnrichmentToolData6
    ) = Field(
        ...,
        description="Every tool payload, for schema emission. Never sent on the wire as a union.",
        title="LibraryEnrichmentToolData",
    )


class ManifestData(BaseModel):
    is_current: bool = Field(..., description="Whether this snapshot is the context's current one.")
    manifest: SnapshotManifest = Field(..., description="The immutable manifest as published.")
