# generated by datamodel-codegen:
#   filename:  worker.schema.json

from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field


class ObservationOrigin(StrEnum):
    source = "source"
    stub = "stub"


class Publicness(BaseModel):
    declared_exports: list[str] = Field(..., description="Literal __all__ entries.")
    docstring: bool = Field(
        ..., description="A docstring exists; absence does not prove private API."
    )
    exported: bool | None = Field(
        ..., description="Membership in a statically resolved __all__, when known."
    )
    reexport: bool = Field(..., description="This is a reexport declaration.")
    underscore: bool = Field(
        ..., description="Underscore naming convention, not a privacy verdict."
    )
    unresolved_exports: list[str] = Field(
        ..., description="Export expressions not statically reduced to literals."
    )


class WorkerFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str = Field(..., description="Archive-relative file path.")
    module: str = Field(..., description="Qualified module import path.")
    origin: ObservationOrigin = Field(..., description="Whether it is .py or .pyi.")


class WorkerGap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str = Field(..., description="Archive path.")
    reason: str = Field(..., description="Why it could not be fully characterized.")


class WorkerRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    files: list[WorkerFile] = Field(
        ..., description="Exhaustive expected file list; worker must account for each."
    )
    max_cpu_seconds: int = Field(
        ..., description="Rust-owned CPU deadline installed before parsing studied source.", ge=0
    )
    max_memory_bytes: int = Field(
        ...,
        description="Rust-owned address-space ceiling installed before parsing studied source.",
        ge=0,
    )
    max_observations: int = Field(..., description="Maximum observations returned.", ge=0)
    root: str = Field(..., description="Absolute service-owned input root.")
    schema_version: str = Field(..., description="Protocol version.")


class Observation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alias_target: str | None = Field(..., description="Alias target even if unresolved.")
    bases: list[str] = Field(
        ..., description="Declared base expressions, not resolved inheritance claims."
    )
    docs: str | None = Field(..., description="Full bounded docstring.")
    file: str = Field(..., description="Relative archive path, never an arbitrary local path.")
    kind: str = Field(..., description="Module, class, function or attribute.")
    line: int | None = Field(..., description="First declaration line.", ge=0)
    origin: ObservationOrigin = Field(..., description="Source versus stub provenance.")
    overloads: list[str] = Field(
        ..., description="Every declared overload, including stub-only overload groups."
    )
    path: str = Field(..., description="Qualified Python path.")
    publicness: Publicness = Field(..., description="Signals remain separate.")
    signature: str | None = Field(..., description="Rendered signature or annotation.")


class WorkerResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gaps: list[WorkerGap] = Field(..., description="Explicit limitations/errors.")
    griffe_version: str = Field(..., description="Griffe version actually used.")
    observations: list[Observation] = Field(..., description="One or more facts per file.")
    processed_files: list[str] = Field(
        ..., description="Files successfully visited, including files with no declarations."
    )
    schema_version: str = Field(..., description="Protocol version.")
    worker_python: str = Field(
        ..., description="The worker's own interpreter, never the analyzed interpreter."
    )


class WorkerProtocol(BaseModel):
    request: WorkerRequest = Field(..., description="Input.")
    response: WorkerResponse = Field(..., description="Output.")
