# generated by datamodel-codegen:
#   filename:  worker.schema.json

from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field


class ObservationOrigin(StrEnum):
    source = "source"
    stub = "stub"


class Publicness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    declared_exports: list[str]
    docstring: bool
    exported: bool | None
    reexport: bool
    underscore: bool
    unresolved_exports: list[str]


class PythonBase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ordinal: int = Field(..., ge=0)
    rendering: str


class PythonDefaultOrigin(StrEnum):
    absent = "absent"
    declared = "declared"
    implicit_variadic = "implicit_variadic"


class PythonParameterKind(StrEnum):
    positional_only = "positional-only"
    positional_or_keyword = "positional or keyword"
    variadic_positional = "variadic positional"
    keyword_only = "keyword-only"
    variadic_keyword = "variadic keyword"


class WorkerFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    module: str
    origin: ObservationOrigin


class WorkerRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    files: list[WorkerFile] = Field(..., max_length=65536, min_length=0)
    max_cpu_seconds: str = Field(
        ...,
        pattern="^(?:1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    max_memory_bytes: str = Field(
        ...,
        pattern="^(?:1(?:0[0-9]{18}|[1-7][0-9]{18}|8(?:0[0-9]{17}|[1-3][0-9]{17}|4(?:0[0-9]{16}|[1-3][0-9]{16}|4(?:0[0-9]{15}|[1-5][0-9]{15}|6(?:0[0-9]{14}|[1-6][0-9]{14}|7(?:0[0-9]{13}|[1-3][0-9]{13}|4(?:0[0-9]{12}|[1-3][0-9]{12}|40(?:0[0-9]{10}|[1-6][0-9]{10}|7(?:0[0-9]{9}|[1-2][0-9]{9}|3(?:0[0-9]{8}|[1-6][0-9]{8}|70(?:0[0-9]{6}|[1-8][0-9]{6}|9(?:0[0-9]{5}|[1-4][0-9]{5}|5(?:0[0-9]{4}|[1-4][0-9]{4}|5(?:0[0-9]{3}|1(?:0[0-9]{2}|[1-5][0-9]{2}|6(?:0[0-9]{1}|1[0-5][0-9]{0}))))))))))))))))|[1-9][0-9]{0,18})$",
    )
    max_observations: str = Field(..., pattern="^(?:100000|[1-9][0-9]{0,4})$")
    root: str
    schema_version: str


class PythonParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    annotation: str | None
    default_origin: PythonDefaultOrigin | None
    kind: PythonParameterKind | None
    name: str
    ordinal: int = Field(..., ge=0)
    reported_default: str | None


class PythonCallable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    labels: list[str]
    parameters: list[PythonParameter]
    returns: str | None


class PythonOverload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    callable: PythonCallable
    ordinal: int = Field(..., ge=0)
    signature: str


class Observation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alias_target: str | None
    bases: list[PythonBase]
    callable: PythonCallable | None
    docs: str | None
    file: str
    kind: str
    line: int | None = Field(..., ge=0)
    origin: ObservationOrigin
    overload_ordinal: int | None = Field(..., ge=0)
    overloads: list[PythonOverload]
    path: str
    publicness: Publicness
    signature: str | None


class WorkerProtocol(BaseModel):
    observation: Observation = Field(
        ..., description="The mechanical observation encoded under the generated Arrow schema."
    )
    request: WorkerRequest = Field(..., description="Input.")
