# generated by datamodel-codegen:
#   filename:  worker.schema.json

from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field


class ObservationOrigin(StrEnum):
    source = "source"
    stub = "stub"


class Publicness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    declared_exports: list[str]
    docstring: bool
    exported: bool | None
    reexport: bool
    underscore: bool
    unresolved_exports: list[str]


class PythonBase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ordinal: int = Field(..., ge=0)
    rendering: str


class PythonDefaultOrigin(StrEnum):
    absent = "absent"
    declared = "declared"
    implicit_variadic = "implicit_variadic"


class PythonParameterKind(StrEnum):
    positional_only = "positional-only"
    positional_or_keyword = "positional or keyword"
    variadic_positional = "variadic positional"
    keyword_only = "keyword-only"
    variadic_keyword = "variadic keyword"


class WorkerFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: str
    module: str
    origin: ObservationOrigin


class WorkerRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    files: list[WorkerFile] = Field(
        ..., description="Exhaustive expected file list; worker must account for each."
    )
    max_cpu_seconds: int = Field(
        ..., description="Rust-owned CPU deadline installed before parsing studied source.", ge=0
    )
    max_memory_bytes: int = Field(
        ...,
        description="Rust-owned address-space ceiling installed before parsing studied source.",
        ge=0,
    )
    max_observations: int = Field(..., description="Maximum observations returned.", ge=0)
    root: str = Field(..., description="Absolute service-owned input root.")
    schema_version: str = Field(..., description="Protocol version.")


class PythonParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    annotation: str | None
    default_origin: PythonDefaultOrigin | None
    kind: PythonParameterKind | None
    name: str
    ordinal: int = Field(..., ge=0)
    reported_default: str | None


class PythonCallable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    labels: list[str]
    parameters: list[PythonParameter]
    returns: str | None


class PythonOverload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    callable: PythonCallable
    ordinal: int = Field(..., ge=0)
    signature: str


class Observation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alias_target: str | None
    bases: list[PythonBase]
    callable: PythonCallable | None
    docs: str | None
    file: str
    kind: str
    line: int | None = Field(..., ge=0)
    origin: ObservationOrigin
    overload_ordinal: int | None = Field(..., ge=0)
    overloads: list[PythonOverload]
    path: str
    publicness: Publicness
    signature: str | None


class WorkerProtocol(BaseModel):
    observation: Observation = Field(
        ..., description="The mechanical observation encoded under the generated Arrow schema."
    )
    request: WorkerRequest = Field(..., description="Input.")
