"""Mechanical validation against the Rust-generated MCP binding catalog."""

from __future__ import annotations

import json
from functools import cache
from typing import Any

from jsonschema import Draft202012Validator
from jsonschema.protocols import Validator

from enrichment_mcp.envelope import SCHEMA_PATH


@cache
def bindings() -> dict[str, dict[str, Any]]:
    """Load the finite operation declaration packaged with its native request schema."""
    schema = json.loads(SCHEMA_PATH.with_name("request.schema.json").read_text())
    return {entry["name"]: entry for entry in schema["x-enrichment-operations"]}


def output_schema(tool: str) -> dict[str, Any]:
    """The daemon's generated response contract, including all native conditional rules."""
    return bindings()[tool]["output_schema"]


@cache
def _output_validator(tool: str) -> Validator:
    return Draft202012Validator(output_schema(tool))


def validate_output(tool: str, result: dict[str, Any]) -> None:
    """Validate without coercing typed native values or inventing defaults."""
    errors = list(_output_validator(tool).iter_errors(result))
    if errors:
        raise ValueError(errors[0].message)


@cache
def delivery_contract() -> dict[str, Any]:
    """Transport facts generated by the native owner."""
    schema = json.loads(SCHEMA_PATH.with_name("request.schema.json").read_text())
    return schema["x-enrichment-mcp-delivery"]
