#!/usr/bin/env bash
# SessionStart | CwdChanged. Gives the agent harness the same environment direnv gives an
# interactive shell, by exporting scripts/env.sh into CLAUDE_ENV_FILE.
#
# The definition lives in scripts/env.sh and is shared with .envrc. Do not add variables
# here -- add them there, so a human and an agent never run against different state.
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/_common.sh"
hook_read_input
root="$(hook_root)"

[ -n "${CLAUDE_ENV_FILE:-}" ] || exit 0
[ -f "${root}/scripts/env.sh" ] || exit 0

# Diff this shell's environment across sourcing env.sh, and emit the result as exports.
python3 - "$root" > "$CLAUDE_ENV_FILE" <<'PY'
import os, subprocess, sys, json

root = sys.argv[1]
script = f'set -a; export LIBENR_ROOT={root!r}; . {root}/scripts/env.sh; python3 -c "import os,json;print(json.dumps(dict(os.environ)))"'
try:
    out = subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=15)
    after = json.loads(out.stdout.strip().splitlines()[-1])
except Exception:
    raise SystemExit

print("# generated by scripts/hooks/session_env.sh from scripts/env.sh -- do not edit")
for k in ("LIBENR_ROOT", "LIBENR_HOME", "LIBENR_CACHE_HOME", "LIBENR_DATA_HOME",
          "LIBENR_CONFIG", "CARGO_TARGET_DIR", "RUST_BACKTRACE", "CARGO_TERM_COLOR",
          "RUSTC_WRAPPER", "UV_PROJECT_ENVIRONMENT", "UV_NO_SYNC",
          "PYTHONDONTWRITEBYTECODE", "PATH"):
    if k in after:
        print(f'export {k}={after[k]!r}')
print("unset RUSTUP_TOOLCHAIN")
PY
exit 0
